# CMake generated Testfile for 
# Source directory: /Users/Rafa/pocs/MaidSafe/src/encrypt
# Build directory: /Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/src/encrypt
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(EncryptStyleCheck "python" "/Users/Rafa/pocs/MaidSafe/tools/cpplint.py" "/Users/Rafa/pocs/MaidSafe/src/encrypt/src/maidsafe/encrypt/byte_array.cc" "/Users/Rafa/pocs/MaidSafe/src/encrypt/src/maidsafe/encrypt/data_map.cc" "/Users/Rafa/pocs/MaidSafe/src/encrypt/src/maidsafe/encrypt/data_map_encryptor.cc" "/Users/Rafa/pocs/MaidSafe/src/encrypt/src/maidsafe/encrypt/self_encryptor.cc" "/Users/Rafa/pocs/MaidSafe/src/encrypt/src/maidsafe/encrypt/tests/benchmark.cc" "/Users/Rafa/pocs/MaidSafe/src/encrypt/src/maidsafe/encrypt/tests/data_map_encryptor_test.cc" "/Users/Rafa/pocs/MaidSafe/src/encrypt/src/maidsafe/encrypt/tests/self_encryptor_basic_test.cc" "/Users/Rafa/pocs/MaidSafe/src/encrypt/src/maidsafe/encrypt/tests/self_encryptor_private_member_test.cc" "/Users/Rafa/pocs/MaidSafe/src/encrypt/src/maidsafe/encrypt/tests/self_encryptor_test.cc" "/Users/Rafa/pocs/MaidSafe/src/encrypt/src/maidsafe/encrypt/tests/test_main.cc" "/Users/Rafa/pocs/MaidSafe/src/encrypt/include/maidsafe/encrypt/data_map.h" "/Users/Rafa/pocs/MaidSafe/src/encrypt/include/maidsafe/encrypt/data_map_encryptor.h" "/Users/Rafa/pocs/MaidSafe/src/encrypt/include/maidsafe/encrypt/self_encryptor.h" "/Users/Rafa/pocs/MaidSafe/src/encrypt/src/maidsafe/encrypt/byte_array.h" "/Users/Rafa/pocs/MaidSafe/src/encrypt/src/maidsafe/encrypt/config.h" "/Users/Rafa/pocs/MaidSafe/src/encrypt/src/maidsafe/encrypt/tests/encrypt_test_base.h" "/Users/Rafa/pocs/MaidSafe/src/encrypt/src/maidsafe/encrypt/xor.h")
set_tests_properties(EncryptStyleCheck PROPERTIES  LABELS "Encrypt;CodingStyle")
add_test(EncryptMultipleDefinitionsCheck "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt_multiple_definitions")
set_tests_properties(EncryptMultipleDefinitionsCheck PROPERTIES  LABELS "Encrypt;MultipleDefinitions")
add_test(EncryptDataMapTest.FUNC_SerialiseParseDataMap "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=EncryptDataMapTest.FUNC_SerialiseParseDataMap" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(EncryptDataMapTest.FUNC_SerialiseParseDataMap PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(EncryptDataMapTest.FUNC_EncryptDecryptDataMap "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=EncryptDataMapTest.FUNC_EncryptDecryptDataMap" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(EncryptDataMapTest.FUNC_EncryptDecryptDataMap PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(EncryptDataMapTest.BEH_DifferentDataMapSameChunk "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=EncryptDataMapTest.BEH_DifferentDataMapSameChunk" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(EncryptDataMapTest.BEH_DifferentDataMapSameChunk PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(EncryptBasicTest.BEH_SMallfileContentOnly "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=EncryptBasicTest.BEH_SMallfileContentOnly" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(EncryptBasicTest.BEH_SMallfileContentOnly PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(EncryptBasicTest.BEH_LargeFileWithLargeGap "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=EncryptBasicTest.BEH_LargeFileWithLargeGap" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(EncryptBasicTest.BEH_LargeFileWithLargeGap PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(PrivateSelfEncryptorTest.BEH_HelpersSmallfileContentOnly "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=PrivateSelfEncryptorTest.BEH_HelpersSmallfileContentOnly" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(PrivateSelfEncryptorTest.BEH_HelpersSmallfileContentOnly PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(PrivateSelfEncryptorTest.BEH_HelpersEqual3MinChunks "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=PrivateSelfEncryptorTest.BEH_HelpersEqual3MinChunks" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(PrivateSelfEncryptorTest.BEH_HelpersEqual3MinChunks PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(PrivateSelfEncryptorTest.BEH_Helpers3MinChunksPlus1 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=PrivateSelfEncryptorTest.BEH_Helpers3MinChunksPlus1" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(PrivateSelfEncryptorTest.BEH_Helpers3MinChunksPlus1 PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(PrivateSelfEncryptorTest.BEH_HelpersEqual3MaxChunks "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=PrivateSelfEncryptorTest.BEH_HelpersEqual3MaxChunks" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(PrivateSelfEncryptorTest.BEH_HelpersEqual3MaxChunks PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(PrivateSelfEncryptorTest.BEH_HelpersMaxChunksPlus1 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=PrivateSelfEncryptorTest.BEH_HelpersMaxChunksPlus1" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(PrivateSelfEncryptorTest.BEH_HelpersMaxChunksPlus1 PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(PrivateSelfEncryptorTest.BEH_HelpersEqual3andaHalfMaxChunks "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=PrivateSelfEncryptorTest.BEH_HelpersEqual3andaHalfMaxChunks" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(PrivateSelfEncryptorTest.BEH_HelpersEqual3andaHalfMaxChunks PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(PrivateSelfEncryptorTest.BEH_HelpersEqual5MaxChunks "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=PrivateSelfEncryptorTest.BEH_HelpersEqual5MaxChunks" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(PrivateSelfEncryptorTest.BEH_HelpersEqual5MaxChunks PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(FileSmallerThanMinFileSize/BasicOffsetTest.FUNC_EncryptDecrypt/0 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileSmallerThanMinFileSize/BasicOffsetTest.FUNC_EncryptDecrypt/0" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileSmallerThanMinFileSize/BasicOffsetTest.FUNC_EncryptDecrypt/0 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileSmallerThanMinFileSize/BasicOffsetTest.FUNC_EncryptDecrypt/1 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileSmallerThanMinFileSize/BasicOffsetTest.FUNC_EncryptDecrypt/1" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileSmallerThanMinFileSize/BasicOffsetTest.FUNC_EncryptDecrypt/1 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileSmallerThanMinFileSize/BasicOffsetTest.FUNC_EncryptDecrypt/2 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileSmallerThanMinFileSize/BasicOffsetTest.FUNC_EncryptDecrypt/2" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileSmallerThanMinFileSize/BasicOffsetTest.FUNC_EncryptDecrypt/2 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileSmallerThanMinFileSize/BasicOffsetTest.FUNC_EncryptDecrypt/3 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileSmallerThanMinFileSize/BasicOffsetTest.FUNC_EncryptDecrypt/3" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileSmallerThanMinFileSize/BasicOffsetTest.FUNC_EncryptDecrypt/3 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileSmallerThanMinFileSize/BasicOffsetTest.FUNC_EncryptDecrypt/4 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileSmallerThanMinFileSize/BasicOffsetTest.FUNC_EncryptDecrypt/4" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileSmallerThanMinFileSize/BasicOffsetTest.FUNC_EncryptDecrypt/4 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileSmallerThanOneChunk/BasicOffsetTest.FUNC_EncryptDecrypt/0 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileSmallerThanOneChunk/BasicOffsetTest.FUNC_EncryptDecrypt/0" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileSmallerThanOneChunk/BasicOffsetTest.FUNC_EncryptDecrypt/0 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileSmallerThanOneChunk/BasicOffsetTest.FUNC_EncryptDecrypt/1 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileSmallerThanOneChunk/BasicOffsetTest.FUNC_EncryptDecrypt/1" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileSmallerThanOneChunk/BasicOffsetTest.FUNC_EncryptDecrypt/1 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileSmallerThanOneChunk/BasicOffsetTest.FUNC_EncryptDecrypt/2 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileSmallerThanOneChunk/BasicOffsetTest.FUNC_EncryptDecrypt/2" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileSmallerThanOneChunk/BasicOffsetTest.FUNC_EncryptDecrypt/2 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileSmallerThanOneChunk/BasicOffsetTest.FUNC_EncryptDecrypt/3 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileSmallerThanOneChunk/BasicOffsetTest.FUNC_EncryptDecrypt/3" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileSmallerThanOneChunk/BasicOffsetTest.FUNC_EncryptDecrypt/3 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileSmallerThanOneChunk/BasicOffsetTest.FUNC_EncryptDecrypt/4 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileSmallerThanOneChunk/BasicOffsetTest.FUNC_EncryptDecrypt/4" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileSmallerThanOneChunk/BasicOffsetTest.FUNC_EncryptDecrypt/4 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/0 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/0" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/0 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/1 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/1" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/1 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/2 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/2" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/2 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/3 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/3" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/3 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/4 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/4" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/4 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/5 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/5" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/5 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/6 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/6" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/6 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/7 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/7" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/7 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/8 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/8" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/8 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/9 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/9" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/9 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/10 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/10" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/10 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/11 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/11" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/11 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/12 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/12" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/12 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/13 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/13" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileSmallerThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/13 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/0 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/0" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/0 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/1 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/1" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/1 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/2 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/2" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/2 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/3 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/3" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/3 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/4 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/4" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/4 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/5 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/5" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/5 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/6 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/6" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/6 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/7 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/7" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/7 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/8 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/8" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/8 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/9 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/9" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/9 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/10 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/10" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/10 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/11 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/11" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/11 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/12 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/12" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/12 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/13 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/13" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/13 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/14 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/14" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/14 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/15 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/15" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileGreaterThanThreeNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/15 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileGreaterThanTenNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/0 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileGreaterThanTenNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/0" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileGreaterThanTenNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/0 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileGreaterThanTenNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/1 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileGreaterThanTenNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/1" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileGreaterThanTenNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/1 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileGreaterThanTenNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/2 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileGreaterThanTenNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/2" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileGreaterThanTenNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/2 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileGreaterThanTenNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/3 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileGreaterThanTenNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/3" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileGreaterThanTenNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/3 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileGreaterThanTenNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/4 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileGreaterThanTenNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/4" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileGreaterThanTenNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/4 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileGreaterThanTenNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/5 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileGreaterThanTenNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/5" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileGreaterThanTenNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/5 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileGreaterThanTenNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/6 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileGreaterThanTenNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/6" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileGreaterThanTenNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/6 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileGreaterThanTenNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/7 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileGreaterThanTenNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/7" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileGreaterThanTenNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/7 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileGreaterThanTenNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/8 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileGreaterThanTenNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/8" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileGreaterThanTenNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/8 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(FileGreaterThanTenNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/9 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=FileGreaterThanTenNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/9" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(FileGreaterThanTenNormalChunks/BasicOffsetTest.FUNC_EncryptDecrypt/9 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(LargeFile/BasicOffsetTest.FUNC_EncryptDecrypt/0 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=LargeFile/BasicOffsetTest.FUNC_EncryptDecrypt/0" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(LargeFile/BasicOffsetTest.FUNC_EncryptDecrypt/0 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(LargeFile/BasicOffsetTest.FUNC_EncryptDecrypt/1 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=LargeFile/BasicOffsetTest.FUNC_EncryptDecrypt/1" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(LargeFile/BasicOffsetTest.FUNC_EncryptDecrypt/1 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(LargeFile/BasicOffsetTest.FUNC_EncryptDecrypt/2 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=LargeFile/BasicOffsetTest.FUNC_EncryptDecrypt/2" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(LargeFile/BasicOffsetTest.FUNC_EncryptDecrypt/2 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "300")
add_test(Writing/SingleBytesTest.BEH_WriteInOrder/0 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Writing/SingleBytesTest.BEH_WriteInOrder/0" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Writing/SingleBytesTest.BEH_WriteInOrder/0 PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(Writing/SingleBytesTest.BEH_WriteInOrder/1 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Writing/SingleBytesTest.BEH_WriteInOrder/1" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Writing/SingleBytesTest.BEH_WriteInOrder/1 PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(Writing/SingleBytesTest.BEH_WriteInOrder/2 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Writing/SingleBytesTest.BEH_WriteInOrder/2" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Writing/SingleBytesTest.BEH_WriteInOrder/2 PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(Writing/SingleBytesTest.BEH_WriteInOrder/3 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Writing/SingleBytesTest.BEH_WriteInOrder/3" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Writing/SingleBytesTest.BEH_WriteInOrder/3 PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(Writing/SingleBytesTest.BEH_WriteInOrder/4 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Writing/SingleBytesTest.BEH_WriteInOrder/4" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Writing/SingleBytesTest.BEH_WriteInOrder/4 PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(Writing/SingleBytesTest.BEH_WriteInOrder/5 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Writing/SingleBytesTest.BEH_WriteInOrder/5" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Writing/SingleBytesTest.BEH_WriteInOrder/5 PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(Writing/SingleBytesTest.BEH_WriteInOrder/6 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Writing/SingleBytesTest.BEH_WriteInOrder/6" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Writing/SingleBytesTest.BEH_WriteInOrder/6 PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(Writing/SingleBytesTest.BEH_WriteAlternatingBytes/0 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Writing/SingleBytesTest.BEH_WriteAlternatingBytes/0" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Writing/SingleBytesTest.BEH_WriteAlternatingBytes/0 PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(Writing/SingleBytesTest.BEH_WriteAlternatingBytes/1 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Writing/SingleBytesTest.BEH_WriteAlternatingBytes/1" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Writing/SingleBytesTest.BEH_WriteAlternatingBytes/1 PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(Writing/SingleBytesTest.BEH_WriteAlternatingBytes/2 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Writing/SingleBytesTest.BEH_WriteAlternatingBytes/2" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Writing/SingleBytesTest.BEH_WriteAlternatingBytes/2 PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(Writing/SingleBytesTest.BEH_WriteAlternatingBytes/3 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Writing/SingleBytesTest.BEH_WriteAlternatingBytes/3" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Writing/SingleBytesTest.BEH_WriteAlternatingBytes/3 PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(Writing/SingleBytesTest.BEH_WriteAlternatingBytes/4 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Writing/SingleBytesTest.BEH_WriteAlternatingBytes/4" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Writing/SingleBytesTest.BEH_WriteAlternatingBytes/4 PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(Writing/SingleBytesTest.BEH_WriteAlternatingBytes/5 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Writing/SingleBytesTest.BEH_WriteAlternatingBytes/5" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Writing/SingleBytesTest.BEH_WriteAlternatingBytes/5 PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(Writing/SingleBytesTest.BEH_WriteAlternatingBytes/6 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Writing/SingleBytesTest.BEH_WriteAlternatingBytes/6" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Writing/SingleBytesTest.BEH_WriteAlternatingBytes/6 PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(Writing/SmallSingleBytesTest.BEH_WriteRandomOrder/0 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Writing/SmallSingleBytesTest.BEH_WriteRandomOrder/0" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Writing/SmallSingleBytesTest.BEH_WriteRandomOrder/0 PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(Writing/SmallSingleBytesTest.BEH_WriteRandomOrder/1 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Writing/SmallSingleBytesTest.BEH_WriteRandomOrder/1" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Writing/SmallSingleBytesTest.BEH_WriteRandomOrder/1 PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(Writing/SmallSingleBytesTest.BEH_WriteRandomOrder/2 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Writing/SmallSingleBytesTest.BEH_WriteRandomOrder/2" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Writing/SmallSingleBytesTest.BEH_WriteRandomOrder/2 PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(Writing/SmallSingleBytesTest.BEH_WriteRandomOrder/3 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Writing/SmallSingleBytesTest.BEH_WriteRandomOrder/3" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Writing/SmallSingleBytesTest.BEH_WriteRandomOrder/3 PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(Writing/SmallSingleBytesTest.BEH_WriteRandomOrder/4 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Writing/SmallSingleBytesTest.BEH_WriteRandomOrder/4" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Writing/SmallSingleBytesTest.BEH_WriteRandomOrder/4 PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(Writing/SmallSingleBytesTest.BEH_WriteRandomOrder/5 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Writing/SmallSingleBytesTest.BEH_WriteRandomOrder/5" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Writing/SmallSingleBytesTest.BEH_WriteRandomOrder/5 PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(Writing/SmallSingleBytesTest.BEH_WriteRandomOrder/6 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Writing/SmallSingleBytesTest.BEH_WriteRandomOrder/6" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Writing/SmallSingleBytesTest.BEH_WriteRandomOrder/6 PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(Reading/InProcessTest.FUNC_ReadInOrder/0 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Reading/InProcessTest.FUNC_ReadInOrder/0" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Reading/InProcessTest.FUNC_ReadInOrder/0 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(Reading/InProcessTest.FUNC_ReadInOrder/1 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Reading/InProcessTest.FUNC_ReadInOrder/1" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Reading/InProcessTest.FUNC_ReadInOrder/1 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(Reading/InProcessTest.FUNC_ReadInOrder/2 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Reading/InProcessTest.FUNC_ReadInOrder/2" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Reading/InProcessTest.FUNC_ReadInOrder/2 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(Reading/InProcessTest.FUNC_ReadInOrder/3 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Reading/InProcessTest.FUNC_ReadInOrder/3" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Reading/InProcessTest.FUNC_ReadInOrder/3 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(Reading/InProcessTest.FUNC_ReadInOrder/4 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Reading/InProcessTest.FUNC_ReadInOrder/4" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Reading/InProcessTest.FUNC_ReadInOrder/4 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(Reading/InProcessTest.FUNC_ReadInOrder/5 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Reading/InProcessTest.FUNC_ReadInOrder/5" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Reading/InProcessTest.FUNC_ReadInOrder/5 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(Reading/InProcessTest.FUNC_ReadInOrder/6 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Reading/InProcessTest.FUNC_ReadInOrder/6" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Reading/InProcessTest.FUNC_ReadInOrder/6 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(Reading/InProcessTest.FUNC_ReadInOrder/7 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Reading/InProcessTest.FUNC_ReadInOrder/7" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Reading/InProcessTest.FUNC_ReadInOrder/7 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(Reading/InProcessTest.FUNC_ReadInOrder/8 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Reading/InProcessTest.FUNC_ReadInOrder/8" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Reading/InProcessTest.FUNC_ReadInOrder/8 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(Reading/InProcessTest.FUNC_ReadInOrder/9 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Reading/InProcessTest.FUNC_ReadInOrder/9" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Reading/InProcessTest.FUNC_ReadInOrder/9 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(Reading/InProcessTest.FUNC_ReadInOrder/10 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Reading/InProcessTest.FUNC_ReadInOrder/10" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Reading/InProcessTest.FUNC_ReadInOrder/10 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(Reading/InProcessTest.FUNC_ReadInOrder/11 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Reading/InProcessTest.FUNC_ReadInOrder/11" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Reading/InProcessTest.FUNC_ReadInOrder/11 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(Reading/InProcessTest.FUNC_ReadInOrder/12 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Reading/InProcessTest.FUNC_ReadInOrder/12" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Reading/InProcessTest.FUNC_ReadInOrder/12 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(Reading/InProcessTest.FUNC_ReadInOrder/13 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Reading/InProcessTest.FUNC_ReadInOrder/13" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Reading/InProcessTest.FUNC_ReadInOrder/13 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(Reading/InProcessTest.FUNC_ReadInOrder/14 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Reading/InProcessTest.FUNC_ReadInOrder/14" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Reading/InProcessTest.FUNC_ReadInOrder/14 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(Reading/InProcessTest.FUNC_ReadInOrder/15 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Reading/InProcessTest.FUNC_ReadInOrder/15" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Reading/InProcessTest.FUNC_ReadInOrder/15 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(Reading/InProcessTest.FUNC_ReadInOrder/16 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Reading/InProcessTest.FUNC_ReadInOrder/16" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Reading/InProcessTest.FUNC_ReadInOrder/16 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(Reading/InProcessTest.FUNC_ReadInOrder/17 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=Reading/InProcessTest.FUNC_ReadInOrder/17" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Reading/InProcessTest.FUNC_ReadInOrder/17 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(BasicTest.FUNC_NewRead "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=BasicTest.FUNC_NewRead" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BasicTest.FUNC_NewRead PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(BasicTest.FUNC_WriteRandomSizeRandomPosition "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=BasicTest.FUNC_WriteRandomSizeRandomPosition" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BasicTest.FUNC_WriteRandomSizeRandomPosition PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(BasicTest.FUNC_RandomSizedOutOfSequenceWritesWithGapsAndOverlaps "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=BasicTest.FUNC_RandomSizedOutOfSequenceWritesWithGapsAndOverlaps" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BasicTest.FUNC_RandomSizedOutOfSequenceWritesWithGapsAndOverlaps PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(BasicTest.FUNC_WriteLongAndShort65536SegmentsReadThenRewrite "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=BasicTest.FUNC_WriteLongAndShort65536SegmentsReadThenRewrite" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BasicTest.FUNC_WriteLongAndShort65536SegmentsReadThenRewrite PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "300")
add_test(BasicTest.FUNC_4096ByteOutOfSequenceWritesReadsAndRewrites "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=BasicTest.FUNC_4096ByteOutOfSequenceWritesReadsAndRewrites" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BasicTest.FUNC_4096ByteOutOfSequenceWritesReadsAndRewrites PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(BasicTest.BEH_DataMapSizes "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=BasicTest.BEH_DataMapSizes" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BasicTest.BEH_DataMapSizes PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BasicTest.BEH_WriteSmallThenAdd "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=BasicTest.BEH_WriteSmallThenAdd" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BasicTest.BEH_WriteSmallThenAdd PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BasicTest.BEH_3SmallChunkRewrite "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=BasicTest.BEH_3SmallChunkRewrite" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BasicTest.BEH_3SmallChunkRewrite PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BasicTest.BEH_nKFile "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=BasicTest.BEH_nKFile" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BasicTest.BEH_nKFile PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BasicTest.BEH_nKFileAppend "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=BasicTest.BEH_nKFileAppend" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BasicTest.BEH_nKFileAppend PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BasicTest.BEH_ManualCheckWrite "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=BasicTest.BEH_ManualCheckWrite" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BasicTest.BEH_ManualCheckWrite PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BasicTest.BEH_TruncateIncreaseScenario1 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=BasicTest.BEH_TruncateIncreaseScenario1" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BasicTest.BEH_TruncateIncreaseScenario1 PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BasicTest.FUNC_TruncateIncreaseScenario2 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=BasicTest.FUNC_TruncateIncreaseScenario2" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BasicTest.FUNC_TruncateIncreaseScenario2 PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(BasicTest.BEH_TruncateDecrease "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=BasicTest.BEH_TruncateDecrease" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BasicTest.BEH_TruncateDecrease PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BasicTest.BEH_TruncateIncreaseDecrease "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=BasicTest.BEH_TruncateIncreaseDecrease" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BasicTest.BEH_TruncateIncreaseDecrease PROPERTIES  LABELS "Encrypt;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BasicTest.FUNC_RandomAccess "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=BasicTest.FUNC_RandomAccess" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BasicTest.FUNC_RandomAccess PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(BasicTest.FUNC_ReadAfterClose "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_encrypt" "--gtest_filter=BasicTest.FUNC_ReadAfterClose" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BasicTest.FUNC_ReadAfterClose PROPERTIES  LABELS "Encrypt;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
