# Generated by CMake 3.0.2

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget maidsafe_common maidsafe_network_viewer maidsafe_test maidsafe_passport maidsafe_rudp maidsafe_routing maidsafe_routing_test_helper maidsafe_encrypt maidsafe_nfs_core maidsafe_nfs_client maidsafe_nfs_vault maidsafe_vault maidsafe_vault_cache_handler maidsafe_vault_data_manager maidsafe_vault_maid_manager maidsafe_vault_mpid_manager maidsafe_vault_pmid_manager maidsafe_vault_pmid_node maidsafe_vault_version_handler maidsafe_vault_mal maidsafe_vault_manager maidsafe_drive maidsafe_drive_launcher maidsafe_api local_drive drive sqlite cryptopp protobuf_lite protoc gmock gtest asio cereal)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target maidsafe_common
add_library(maidsafe_common STATIC IMPORTED)

set_target_properties(maidsafe_common PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "APPLICATION_VERSION_MAJOR=0;APPLICATION_VERSION_MINOR=2;APPLICATION_VERSION_PATCH=002;TARGET_PLATFORM=OSX10.10;TARGET_ARCHITECTURE=x86_64;$<$<BOOL:ON>:TESTING>;$<$<BOOL:>:USE_PROFILING>;$<$<BOOL:>:USE_LOGGING=1>;$<$<BOOL:>:USE_LOGGING=0>;$<$<BOOL:OFF>:USE_VLOGGING>;BOOST_ASIO_HAS_MOVE;BOOST_ASIO_HAS_STD_ARRAY;BOOST_ASIO_HAS_STD_ATOMIC;BOOST_ASIO_HAS_STD_SHARED_PTR;BOOST_ASIO_HAS_STD_CHRONO;BOOST_FILESYSTEM_NO_DEPRECATED;BOOST_FILESYSTEM_VERSION=3;BOOST_PYTHON_STATIC_LIB;BOOST_THREAD_VERSION=4;BOOST_RESULT_OF_USE_DECLTYPE;$<$<BOOL:>:MAIDSAFE_WIN32>;$<$<BOOL:>:MAIDSAFE_WIN64>;$<$<BOOL:>:;WIN32_LEAN_AND_MEAN;_WIN32_WINNT=0x0600;_UNICODE;UNICODE;_BIND_TO_CURRENT_VCLIBS_VERSION=1;_VARIADIC_MAX=10;NOMINMAX;BOOST_ALL_NO_LIB;>;$<$<BOOL:1>:;_FILE_OFFSET_BITS=64;HAVE_PTHREAD;$<$<BOOL:1>:MAIDSAFE_APPLE>;$<$<BOOL:>:MAIDSAFE_BSD>;$<$<NOT:$<BOOL:1>>:MAIDSAFE_LINUX>;$<$<CONFIG:Release>:_FORTIFY_SOURCE=2>;>;$<$<CONFIG:Release>:NDEBUG>;$<$<AND:$<BOOL:>,$<CONFIG:Debug>>:_JUST_THREAD_DEADLOCK_CHECK>;$<$<BOOL:ON>:BOOST_DISABLE_ASSERTS>"
  INTERFACE_COMPILE_OPTIONS "-isystem/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/boost_1_57_0_Clang_6_0_0_6000054_LibCXX;$<$<BOOL:>:;/W4;/WX;/MP7;/EHsc;/TP;/wd4351;/wd4503;/wd4512;/wd4913;/wd4996;/wd4714;$<$<CONFIG:Release>:;/O2;/GL;/MD;>;$<$<CONFIG:Debug>:;/Zi;/Od;/RTC1;/MDd;>;$<$<CONFIG:MinSizeRel>:;/MD;>;$<$<CONFIG:RelWithDebInfo>:;/O2;/GL;/MD;/Zi;>;>;$<$<BOOL:1>:;-std=c++11;-pthread;-W;-Werror;-Wall;-Wextra;-Wunused-parameter;-Wno-system-headers;-Wno-deprecated;-Wwrite-strings;-Wundef;-Wuninitialized;-Wparentheses;-Wfloat-equal;-Wstrict-overflow;-Wstrict-overflow=5;-Wredundant-decls;-fPIC;-pedantic;-pedantic-errors;$<$<CONFIG:Debug>:;-O0;-fno-inline;-fno-eliminate-unused-debug-types;-g3;-ggdb;>;$<$<CONFIG:Release>:-O2>;$<$<OR:$<CXX_COMPILER_ID:Clang>,$<CXX_COMPILER_ID:AppleClang>>:;-stdlib=libc++;$<$<CONFIG:Debug>:;-fdiagnostics-format=clang;-fdiagnostics-show-option;-fdiagnostics-fixit-info;-Wno-unused-command-line-argument;>;>;$<$<CXX_COMPILER_ID:GNU>:-static-libstdc++>;>"
  INTERFACE_INCLUDE_DIRECTORIES "/Users/Rafa/pocs/MaidSafe/src/common/include"
  INTERFACE_LINK_LIBRARIES "maidsafe_passport;asio;cereal;cryptopp;sqlite;BoostChrono;BoostDateTime;BoostFilesystem;BoostLocale;/usr/lib/libiconv.dylib;BoostRegex;BoostSystem;BoostThread;BoostProgramOptions"
)

# Create imported target maidsafe_network_viewer
add_library(maidsafe_network_viewer STATIC IMPORTED)

set_target_properties(maidsafe_network_viewer PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/Rafa/pocs/MaidSafe/src/common/include"
  INTERFACE_LINK_LIBRARIES "maidsafe_common"
)

# Create imported target maidsafe_test
add_library(maidsafe_test STATIC IMPORTED)

set_target_properties(maidsafe_test PROPERTIES
  INTERFACE_LINK_LIBRARIES "maidsafe_common;gtest"
)

# Create imported target maidsafe_passport
add_library(maidsafe_passport STATIC IMPORTED)

set_target_properties(maidsafe_passport PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/Rafa/pocs/MaidSafe/src/passport/include"
  INTERFACE_LINK_LIBRARIES "maidsafe_common"
)

# Create imported target maidsafe_rudp
add_library(maidsafe_rudp STATIC IMPORTED)

set_target_properties(maidsafe_rudp PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/Rafa/pocs/MaidSafe/src/rudp/include"
  INTERFACE_LINK_LIBRARIES "maidsafe_common"
)

# Create imported target maidsafe_routing
add_library(maidsafe_routing STATIC IMPORTED)

set_target_properties(maidsafe_routing PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/Rafa/pocs/MaidSafe/src/routing/include;/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/GeneratedProtoFiles"
  INTERFACE_LINK_LIBRARIES "maidsafe_rudp;maidsafe_passport;maidsafe_network_viewer;protobuf_lite;maidsafe_network_viewer"
)

# Create imported target maidsafe_routing_test_helper
add_library(maidsafe_routing_test_helper STATIC IMPORTED)

set_target_properties(maidsafe_routing_test_helper PROPERTIES
  INTERFACE_LINK_LIBRARIES "maidsafe_routing;maidsafe_test"
)

# Create imported target maidsafe_encrypt
add_library(maidsafe_encrypt STATIC IMPORTED)

set_target_properties(maidsafe_encrypt PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/Rafa/pocs/MaidSafe/src/encrypt/include;/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/GeneratedProtoFiles"
  INTERFACE_LINK_LIBRARIES "maidsafe_common;protobuf_lite"
)

# Create imported target maidsafe_nfs_core
add_library(maidsafe_nfs_core STATIC IMPORTED)

set_target_properties(maidsafe_nfs_core PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/GeneratedProtoFiles;/Users/Rafa/pocs/MaidSafe/src/nfs/include;/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/GeneratedSources/nfs/include"
  INTERFACE_LINK_LIBRARIES "maidsafe_routing;protobuf_lite"
)

# Create imported target maidsafe_nfs_client
add_library(maidsafe_nfs_client STATIC IMPORTED)

set_target_properties(maidsafe_nfs_client PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/Rafa/pocs/MaidSafe/src/nfs/include;/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/GeneratedSources/nfs/include"
  INTERFACE_LINK_LIBRARIES "maidsafe_nfs_vault;maidsafe_nfs_core"
)

# Create imported target maidsafe_nfs_vault
add_library(maidsafe_nfs_vault STATIC IMPORTED)

set_target_properties(maidsafe_nfs_vault PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/Rafa/pocs/MaidSafe/src/nfs/include;/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/GeneratedSources/nfs/include"
  INTERFACE_LINK_LIBRARIES "maidsafe_nfs_client;maidsafe_nfs_core"
)

# Create imported target maidsafe_vault
add_library(maidsafe_vault STATIC IMPORTED)

set_target_properties(maidsafe_vault PROPERTIES
  INTERFACE_COMPILE_OPTIONS "$<$<AND:$<BOOL:>,$<OR:$<CONFIG:Release>,$<CONFIG:RelWithDebInfo>>>:/wd4702>"
  INTERFACE_INCLUDE_DIRECTORIES "/Users/Rafa/pocs/MaidSafe/src/vault/include;/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/GeneratedProtoFiles"
  INTERFACE_LINK_LIBRARIES "maidsafe_vault_manager;maidsafe_nfs_vault;maidsafe_vault_cache_handler;maidsafe_vault_data_manager;maidsafe_vault_maid_manager;maidsafe_vault_mpid_manager;maidsafe_vault_pmid_manager;maidsafe_vault_pmid_node;maidsafe_vault_version_handler"
)

# Create imported target maidsafe_vault_cache_handler
add_library(maidsafe_vault_cache_handler STATIC IMPORTED)

set_target_properties(maidsafe_vault_cache_handler PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/Rafa/pocs/MaidSafe/src/vault/include;/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/GeneratedProtoFiles"
  INTERFACE_LINK_LIBRARIES "maidsafe_vault;maidsafe_nfs_vault;protobuf_lite"
)

# Create imported target maidsafe_vault_data_manager
add_library(maidsafe_vault_data_manager STATIC IMPORTED)

set_target_properties(maidsafe_vault_data_manager PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/Rafa/pocs/MaidSafe/src/vault/include;/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/GeneratedProtoFiles"
  INTERFACE_LINK_LIBRARIES "maidsafe_vault;maidsafe_nfs_vault;protobuf_lite"
)

# Create imported target maidsafe_vault_maid_manager
add_library(maidsafe_vault_maid_manager STATIC IMPORTED)

set_target_properties(maidsafe_vault_maid_manager PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/Rafa/pocs/MaidSafe/src/vault/include;/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/GeneratedProtoFiles"
  INTERFACE_LINK_LIBRARIES "maidsafe_vault;maidsafe_nfs_vault;protobuf_lite"
)

# Create imported target maidsafe_vault_mpid_manager
add_library(maidsafe_vault_mpid_manager STATIC IMPORTED)

set_target_properties(maidsafe_vault_mpid_manager PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/Rafa/pocs/MaidSafe/src/vault/include;/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/GeneratedProtoFiles"
  INTERFACE_LINK_LIBRARIES "maidsafe_vault;maidsafe_nfs_vault;protobuf_lite"
)

# Create imported target maidsafe_vault_pmid_manager
add_library(maidsafe_vault_pmid_manager STATIC IMPORTED)

set_target_properties(maidsafe_vault_pmid_manager PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/Rafa/pocs/MaidSafe/src/vault/include;/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/GeneratedProtoFiles"
  INTERFACE_LINK_LIBRARIES "maidsafe_vault;maidsafe_nfs_vault;protobuf_lite"
)

# Create imported target maidsafe_vault_pmid_node
add_library(maidsafe_vault_pmid_node STATIC IMPORTED)

set_target_properties(maidsafe_vault_pmid_node PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/Rafa/pocs/MaidSafe/src/vault/include;/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/GeneratedProtoFiles"
  INTERFACE_LINK_LIBRARIES "maidsafe_vault;maidsafe_nfs_vault;protobuf_lite"
)

# Create imported target maidsafe_vault_version_handler
add_library(maidsafe_vault_version_handler STATIC IMPORTED)

set_target_properties(maidsafe_vault_version_handler PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/Rafa/pocs/MaidSafe/src/vault/include;/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/GeneratedProtoFiles"
  INTERFACE_LINK_LIBRARIES "maidsafe_vault;maidsafe_nfs_vault;protobuf_lite"
)

# Create imported target maidsafe_vault_mal
add_library(maidsafe_vault_mal STATIC IMPORTED)

set_target_properties(maidsafe_vault_mal PROPERTIES
  INTERFACE_COMPILE_OPTIONS "$<$<AND:$<BOOL:>,$<OR:$<CONFIG:Release>,$<CONFIG:RelWithDebInfo>>>:/wd4702>"
  INTERFACE_INCLUDE_DIRECTORIES "/Users/Rafa/pocs/MaidSafe/src/vault/include;/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/GeneratedProtoFiles"
  INTERFACE_LINK_LIBRARIES "maidsafe_vault_manager;maidsafe_nfs_vault;protobuf_lite"
)

# Create imported target maidsafe_vault_manager
add_library(maidsafe_vault_manager STATIC IMPORTED)

set_target_properties(maidsafe_vault_manager PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/GeneratedProtoFiles;/Users/Rafa/pocs/MaidSafe/src/vault_manager/include"
  INTERFACE_LINK_LIBRARIES "maidsafe_nfs_client;protobuf_lite"
)

# Create imported target maidsafe_drive
add_library(maidsafe_drive STATIC IMPORTED)

set_target_properties(maidsafe_drive PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "$<$<BOOL:1>:FUSE_USE_VERSION=26>"
  INTERFACE_INCLUDE_DIRECTORIES "/Users/Rafa/pocs/MaidSafe/src/drive/include;/usr/local/include/osxfuse"
  INTERFACE_LINK_LIBRARIES "/usr/local/lib/libosxfuse_i64.dylib;maidsafe_drive_launcher;maidsafe_encrypt"
)

# Create imported target maidsafe_drive_launcher
add_library(maidsafe_drive_launcher STATIC IMPORTED)

set_target_properties(maidsafe_drive_launcher PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/Rafa/pocs/MaidSafe/src/drive/include;/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/GeneratedProtoFiles"
  INTERFACE_LINK_LIBRARIES "maidsafe_common;maidsafe_nfs_client;protobuf_lite"
)

# Create imported target maidsafe_api
add_library(maidsafe_api STATIC IMPORTED)

set_target_properties(maidsafe_api PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/GeneratedProtoFiles;/Users/Rafa/pocs/MaidSafe/src/api/include"
  INTERFACE_LINK_LIBRARIES "maidsafe_nfs_client;maidsafe_passport;maidsafe_encrypt;protobuf_lite"
)

# Create imported target local_drive
add_executable(local_drive IMPORTED)

# Create imported target drive
add_executable(drive IMPORTED)

# Create imported target sqlite
add_library(sqlite STATIC IMPORTED)

set_target_properties(sqlite PROPERTIES
  INTERFACE_COMPILE_OPTIONS "-isystem/Users/Rafa/pocs/MaidSafe/src/third_party_libs/sqlite/include"
  INTERFACE_LINK_LIBRARIES "-lpthread"
)

# Create imported target cryptopp
add_library(cryptopp STATIC IMPORTED)

set_target_properties(cryptopp PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "$<$<OR:$<CXX_COMPILER_ID:Clang>,$<CXX_COMPILER_ID:AppleClang>>:CRYPTOPP_DISABLE_ASM;CRYPTOPP_DISABLE_UNCAUGHT_EXCEPTION>;$<$<AND:$<BOOL:>,$<CONFIG:Debug>>:_JUST_THREAD_DEADLOCK_CHECK>"
  INTERFACE_COMPILE_OPTIONS "-isystem/Users/Rafa/pocs/MaidSafe/src/third_party_libs/cryptopp/..;$<$<BOOL:>:;$<$<CONFIG:Release>:/O2;/GL;/MD>;$<$<CONFIG:Debug>:/Od;/MDd;/Zi>;$<$<CONFIG:MinSizeRel>:/MD>;$<$<CONFIG:RelWithDebInfo>:/O2;/GL;/MD;/Zi>;>;$<$<BOOL:1>:-std=c++11;-pthread;-stdlib=libc++>"
)

# Create imported target protobuf_lite
add_library(protobuf_lite STATIC IMPORTED)

set_target_properties(protobuf_lite PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "HAVE_HASH_MAP=1;HAVE_HASH_SET=1;HASH_NAMESPACE=std;HASH_MAP_H=<unordered_map>;HASH_SET_H=<unordered_set>;HASH_MAP_CLASS=unordered_map;HASH_SET_CLASS=unordered_set;HAVE_ZLIB=0;$<$<AND:$<BOOL:>,$<CONFIG:Debug>>:_JUST_THREAD_DEADLOCK_CHECK>;$<$<BOOL:>:NOMINMAX>"
  INTERFACE_COMPILE_OPTIONS "-isystem/Users/Rafa/pocs/MaidSafe/src/third_party_libs/protobuf/src;$<$<BOOL:>:;$<$<CONFIG:Release>:/O2;/GL;/MD>;$<$<CONFIG:Debug>:/Od;/MDd;/Zi>;$<$<CONFIG:MinSizeRel>:/MD>;$<$<CONFIG:RelWithDebInfo>:/O2;/GL;/MD;/Zi>;>;$<$<BOOL:1>:-std=c++11;-fPIC;-stdlib=libc++>"
)

# Create imported target protoc
add_executable(protoc IMPORTED)

# Create imported target gmock
add_library(gmock STATIC IMPORTED)

set_target_properties(gmock PROPERTIES
  INTERFACE_COMPILE_OPTIONS "-isystem/Users/Rafa/pocs/MaidSafe/src/third_party_libs/googlemock/include"
  INTERFACE_LINK_LIBRARIES "gtest"
)

# Create imported target gtest
add_library(gtest STATIC IMPORTED)

set_target_properties(gtest PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "GTEST_DONT_DEFINE_FAIL=1;GTEST_DONT_DEFINE_SUCCEED=1;GTEST_USE_OWN_TUPLE=0;USE_MAIDSAFE_LOG=1;$<$<OR:$<CXX_COMPILER_ID:Clang>,$<CXX_COMPILER_ID:AppleClang>>:_FILE_OFFSET_BITS=64>"
  INTERFACE_COMPILE_OPTIONS "-isystem/Users/Rafa/pocs/MaidSafe/src/third_party_libs/googlemock/gtest/include"
  INTERFACE_LINK_LIBRARIES "maidsafe_common"
)

# Create imported target asio
add_library(asio INTERFACE IMPORTED)

set_target_properties(asio PROPERTIES
  INTERFACE_COMPILE_OPTIONS "-isystem/Users/Rafa/pocs/MaidSafe/src/third_party_libs/header_only"
  INTERFACE_LINK_LIBRARIES "BoostCoroutine;BoostContext;BoostSystem"
)

# Create imported target cereal
add_library(cereal INTERFACE IMPORTED)

set_target_properties(cereal PROPERTIES
  INTERFACE_COMPILE_OPTIONS "-isystem/Users/Rafa/pocs/MaidSafe/src/third_party_libs/header_only"
)

# Import target "maidsafe_common" for configuration "Debug"
set_property(TARGET maidsafe_common APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(maidsafe_common PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/libmaidsafe_common-d.a"
  )

# Import target "maidsafe_network_viewer" for configuration "Debug"
set_property(TARGET maidsafe_network_viewer APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(maidsafe_network_viewer PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/libmaidsafe_network_viewer-d.a"
  )

# Import target "maidsafe_test" for configuration "Debug"
set_property(TARGET maidsafe_test APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(maidsafe_test PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/libmaidsafe_test-d.a"
  )

# Import target "maidsafe_passport" for configuration "Debug"
set_property(TARGET maidsafe_passport APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(maidsafe_passport PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/libmaidsafe_passport-d.a"
  )

# Import target "maidsafe_rudp" for configuration "Debug"
set_property(TARGET maidsafe_rudp APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(maidsafe_rudp PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/libmaidsafe_rudp-d.a"
  )

# Import target "maidsafe_routing" for configuration "Debug"
set_property(TARGET maidsafe_routing APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(maidsafe_routing PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/libmaidsafe_routing-d.a"
  )

# Import target "maidsafe_routing_test_helper" for configuration "Debug"
set_property(TARGET maidsafe_routing_test_helper APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(maidsafe_routing_test_helper PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/libmaidsafe_routing_test_helper-d.a"
  )

# Import target "maidsafe_encrypt" for configuration "Debug"
set_property(TARGET maidsafe_encrypt APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(maidsafe_encrypt PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/libmaidsafe_encrypt-d.a"
  )

# Import target "maidsafe_nfs_core" for configuration "Debug"
set_property(TARGET maidsafe_nfs_core APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(maidsafe_nfs_core PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/libmaidsafe_nfs_core-d.a"
  )

# Import target "maidsafe_nfs_client" for configuration "Debug"
set_property(TARGET maidsafe_nfs_client APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(maidsafe_nfs_client PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/libmaidsafe_nfs_client-d.a"
  )

# Import target "maidsafe_nfs_vault" for configuration "Debug"
set_property(TARGET maidsafe_nfs_vault APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(maidsafe_nfs_vault PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/libmaidsafe_nfs_vault-d.a"
  )

# Import target "maidsafe_vault" for configuration "Debug"
set_property(TARGET maidsafe_vault APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(maidsafe_vault PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/libmaidsafe_vault-d.a"
  )

# Import target "maidsafe_vault_cache_handler" for configuration "Debug"
set_property(TARGET maidsafe_vault_cache_handler APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(maidsafe_vault_cache_handler PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/libmaidsafe_vault_cache_handler-d.a"
  )

# Import target "maidsafe_vault_data_manager" for configuration "Debug"
set_property(TARGET maidsafe_vault_data_manager APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(maidsafe_vault_data_manager PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/libmaidsafe_vault_data_manager-d.a"
  )

# Import target "maidsafe_vault_maid_manager" for configuration "Debug"
set_property(TARGET maidsafe_vault_maid_manager APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(maidsafe_vault_maid_manager PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/libmaidsafe_vault_maid_manager-d.a"
  )

# Import target "maidsafe_vault_mpid_manager" for configuration "Debug"
set_property(TARGET maidsafe_vault_mpid_manager APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(maidsafe_vault_mpid_manager PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/libmaidsafe_vault_mpid_manager-d.a"
  )

# Import target "maidsafe_vault_pmid_manager" for configuration "Debug"
set_property(TARGET maidsafe_vault_pmid_manager APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(maidsafe_vault_pmid_manager PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/libmaidsafe_vault_pmid_manager-d.a"
  )

# Import target "maidsafe_vault_pmid_node" for configuration "Debug"
set_property(TARGET maidsafe_vault_pmid_node APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(maidsafe_vault_pmid_node PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/libmaidsafe_vault_pmid_node-d.a"
  )

# Import target "maidsafe_vault_version_handler" for configuration "Debug"
set_property(TARGET maidsafe_vault_version_handler APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(maidsafe_vault_version_handler PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/libmaidsafe_vault_version_handler-d.a"
  )

# Import target "maidsafe_vault_mal" for configuration "Debug"
set_property(TARGET maidsafe_vault_mal APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(maidsafe_vault_mal PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/libmaidsafe_vault_mal-d.a"
  )

# Import target "maidsafe_vault_manager" for configuration "Debug"
set_property(TARGET maidsafe_vault_manager APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(maidsafe_vault_manager PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/libmaidsafe_vault_manager-d.a"
  )

# Import target "maidsafe_drive" for configuration "Debug"
set_property(TARGET maidsafe_drive APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(maidsafe_drive PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/libmaidsafe_drive-d.a"
  )

# Import target "maidsafe_drive_launcher" for configuration "Debug"
set_property(TARGET maidsafe_drive_launcher APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(maidsafe_drive_launcher PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/libmaidsafe_drive_launcher-d.a"
  )

# Import target "maidsafe_api" for configuration "Debug"
set_property(TARGET maidsafe_api APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(maidsafe_api PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/libmaidsafe_api-d.a"
  )

# Import target "local_drive" for configuration "Debug"
set_property(TARGET local_drive APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(local_drive PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/local_drive"
  )

# Import target "drive" for configuration "Debug"
set_property(TARGET drive APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(drive PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/drive"
  )

# Import target "sqlite" for configuration "Debug"
set_property(TARGET sqlite APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(sqlite PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/libsqlite-d.a"
  )

# Import target "cryptopp" for configuration "Debug"
set_property(TARGET cryptopp APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(cryptopp PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/libcryptopp-d.a"
  )

# Import target "protobuf_lite" for configuration "Debug"
set_property(TARGET protobuf_lite APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(protobuf_lite PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/libprotobuf_lite-d.a"
  )

# Import target "protoc" for configuration "Debug"
set_property(TARGET protoc APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(protoc PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/protoc"
  )

# Import target "gmock" for configuration "Debug"
set_property(TARGET gmock APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(gmock PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/libgmock.a"
  )

# Import target "gtest" for configuration "Debug"
set_property(TARGET gtest APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(gtest PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/libgtest.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
