# CMake generated Testfile for 
# Source directory: /Users/Rafa/pocs/MaidSafe/src/common
# Build directory: /Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/src/common
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(CommonStyleCheck "python" "/Users/Rafa/pocs/MaidSafe/tools/cpplint.py" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/active.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/asio_service.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/authentication/detail/secure_string.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/authentication/tests/secure_string_test.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/authentication/tests/user_credential_utils_test.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/authentication/user_credential_utils.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/cli.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/clock.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/config.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/containers/tests/lru_cache_test.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/crypto.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/data_buffer.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/data_types/immutable_data.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/data_types/mutable_data.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/data_types/structured_data_versions.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/data_types/tests/data_types_test.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/data_types/tests/mutable_data_test.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/data_types/tests/structured_data_versions_test.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/error.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/error_categories.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/ipc.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/log.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/menu.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/menu_item.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/node_id.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/process.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/profiler.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/rsa.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/serialisation/tests/binary_archive_test.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/sqlite3_wrapper.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/tcp/connection.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/tcp/listener.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/tcp/tests/tcp_test.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/test.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/tests/asio_service_test.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/tests/bounded_string_test.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/tests/cli_test.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/tests/clock_test.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/tests/config_test.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/tests/crypto_test.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/tests/data_buffer_test.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/tests/data_buffer_unit_test.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/tests/errors_test.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/tests/ipc_child_process.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/tests/ipc_test.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/tests/make_unique_test.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/tests/node_id_test.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/tests/on_scope_exit_test.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/tests/rsa_test.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/tests/sqlite3_test.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/tests/tests_main.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/tests/utils_test.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/tests/visualiser_log_test.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/tools/address_space_tool.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/tools/bootstrap_file_tool.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/tools/download_manager.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/tools/network_viewer.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/tools/qa_tool.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/tools/signing_tool.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/tools/sqlite_wrapper_benchmark.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/tools/tests/benchmark/sqlite3_wrapper_benchmark.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/tools/tests/bootstrap_file_tool_test.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/tools/tests/download_manager_test.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/tools/tests/network_viewer_test.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/utils.cc" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/visualiser_log.cc" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/active.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/application_support_directories.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/asio_service.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/authentication/detail/safe_allocators.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/authentication/detail/secure_string.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/authentication/user_credential_utils.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/authentication/user_credentials.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/bounded_string.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/cli.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/clock.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/config.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/containers/lru_cache.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/crypto.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/data_buffer.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/data_types/data_name_variant.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/data_types/data_type_macros.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/data_types/data_type_values.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/data_types/immutable_data.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/data_types/mutable_data.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/data_types/structured_data_versions.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/error.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/ipc.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/log.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/make_unique.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/menu.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/menu_item.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/node_id.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/on_scope_exit.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/process.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/profiler.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/rsa.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/safe_queue.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/serialisation/binary_archive.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/serialisation/compile_time_mapper.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/serialisation/serialisation.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/sqlite3_wrapper.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/tagged_value.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/tcp/connection.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/tcp/listener.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/test.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/tools/network_viewer.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/tools/sqlite3_wrapper_benchmark.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/type_check.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/type_macros.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/types.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/utils.h" "/Users/Rafa/pocs/MaidSafe/src/common/include/maidsafe/common/visualiser_log.h" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/data_types/structured_data_versions_cereal.h" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/data_types/version_cereal.h" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/error_categories.h" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/node_id_common_bits_matrix.h" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/safe_encrypt_cereal.h" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/tools/address_space_tool.h" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/tools/bootstrap_file_tool_cereal.h" "/Users/Rafa/pocs/MaidSafe/src/common/src/maidsafe/common/tools/download_manager.h")
set_tests_properties(CommonStyleCheck PROPERTIES  LABELS "Common;CodingStyle")
add_test(CommonMultipleDefinitionsCheck "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common_multiple_definitions")
set_tests_properties(CommonMultipleDefinitionsCheck PROPERTIES  LABELS "Common;MultipleDefinitions")
add_test(AsioServiceTest.BEH_StartAndStop "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=AsioServiceTest.BEH_StartAndStop" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(AsioServiceTest.BEH_StartAndStop PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BoundedStringTest.BEH_DefaultConstructor "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=BoundedStringTest.BEH_DefaultConstructor" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BoundedStringTest.BEH_DefaultConstructor PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BoundedStringTest.BEH_Getters "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=BoundedStringTest.BEH_Getters" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BoundedStringTest.BEH_Getters PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BoundedStringTest.BEH_StringConstructor "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=BoundedStringTest.BEH_StringConstructor" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BoundedStringTest.BEH_StringConstructor PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BoundedStringTest.BEH_Swap "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=BoundedStringTest.BEH_Swap" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BoundedStringTest.BEH_Swap PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BoundedStringTest.BEH_Copy "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=BoundedStringTest.BEH_Copy" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BoundedStringTest.BEH_Copy PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BoundedStringTest.BEH_Move "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=BoundedStringTest.BEH_Move" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BoundedStringTest.BEH_Move PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BoundedStringTest.BEH_Assignment "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=BoundedStringTest.BEH_Assignment" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BoundedStringTest.BEH_Assignment PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BoundedStringTest.BEH_CopyConstructor "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=BoundedStringTest.BEH_CopyConstructor" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BoundedStringTest.BEH_CopyConstructor PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BoundedStringTest.BEH_CopyAssignment "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=BoundedStringTest.BEH_CopyAssignment" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BoundedStringTest.BEH_CopyAssignment PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BoundedStringTest.BEH_Concatenation "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=BoundedStringTest.BEH_Concatenation" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BoundedStringTest.BEH_Concatenation PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BoundedStringTest.BEH_Serialization "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=BoundedStringTest.BEH_Serialization" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BoundedStringTest.BEH_Serialization PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(CliTest.BEH_GetTest "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=CliTest.BEH_GetTest" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(CliTest.BEH_GetTest PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(CliTest.BEH_MenuFunctions "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=CliTest.BEH_MenuFunctions" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(CliTest.BEH_MenuFunctions PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(CliTest.BEH_MenuHierarchy "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=CliTest.BEH_MenuHierarchy" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(CliTest.BEH_MenuHierarchy PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(CliTokenTest.BEH_TokenTest "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=CliTokenTest.BEH_TokenTest" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(CliTokenTest.BEH_TokenTest PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(ClockTest.BEH_TimeConversion "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=ClockTest.BEH_TimeConversion" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(ClockTest.BEH_TimeConversion PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(ClockTest.BEH_TimePointConversion "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=ClockTest.BEH_TimePointConversion" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(ClockTest.BEH_TimePointConversion PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(CryptoTest.FUNC_Obfuscation "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=CryptoTest.FUNC_Obfuscation" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(CryptoTest.FUNC_Obfuscation PROPERTIES  LABELS "Common;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(CryptoTest.BEH_Xor "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=CryptoTest.BEH_Xor" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(CryptoTest.BEH_Xor PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(CryptoTest.BEH_SecurePasswordGeneration "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=CryptoTest.BEH_SecurePasswordGeneration" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(CryptoTest.BEH_SecurePasswordGeneration PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(CryptoTest.BEH_Hash "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=CryptoTest.BEH_Hash" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(CryptoTest.BEH_Hash PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(CryptoTest.BEH_SymmEncrypt "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=CryptoTest.BEH_SymmEncrypt" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(CryptoTest.BEH_SymmEncrypt PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(CryptoTest.BEH_Compress "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=CryptoTest.BEH_Compress" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(CryptoTest.BEH_Compress PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(CryptoTest.BEH_GzipSHA512Deterministic "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=CryptoTest.BEH_GzipSHA512Deterministic" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(CryptoTest.BEH_GzipSHA512Deterministic PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(DataBufferTest.BEH_Constructor "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=DataBufferTest.BEH_Constructor" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(DataBufferTest.BEH_Constructor PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(DataBufferTest.BEH_Destructor "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=DataBufferTest.BEH_Destructor" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(DataBufferTest.BEH_Destructor PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(DataBufferTest.BEH_SetMaxDiskMemoryUsage "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=DataBufferTest.BEH_SetMaxDiskMemoryUsage" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(DataBufferTest.BEH_SetMaxDiskMemoryUsage PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(DataBufferTest.BEH_RemoveDiskBuffer "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=DataBufferTest.BEH_RemoveDiskBuffer" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(DataBufferTest.BEH_RemoveDiskBuffer PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(DataBufferTest.BEH_SuccessfulStore "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=DataBufferTest.BEH_SuccessfulStore" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(DataBufferTest.BEH_SuccessfulStore PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(DataBufferTest.BEH_UnsuccessfulStore "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=DataBufferTest.BEH_UnsuccessfulStore" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(DataBufferTest.BEH_UnsuccessfulStore PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(DataBufferTest.BEH_DeleteOnDiskBufferOverfill "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=DataBufferTest.BEH_DeleteOnDiskBufferOverfill" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(DataBufferTest.BEH_DeleteOnDiskBufferOverfill PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(DataBufferTest.BEH_PopOnDiskBufferOverfill "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=DataBufferTest.BEH_PopOnDiskBufferOverfill" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(DataBufferTest.BEH_PopOnDiskBufferOverfill PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(DataBufferTest.BEH_AsyncDeleteOnDiskBufferOverfill "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=DataBufferTest.BEH_AsyncDeleteOnDiskBufferOverfill" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(DataBufferTest.BEH_AsyncDeleteOnDiskBufferOverfill PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(DataBufferTest.BEH_AsyncPopOnDiskBufferOverfill "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=DataBufferTest.BEH_AsyncPopOnDiskBufferOverfill" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(DataBufferTest.BEH_AsyncPopOnDiskBufferOverfill PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(DataBufferTest.BEH_RepeatedlyStoreUsingSameKey "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=DataBufferTest.BEH_RepeatedlyStoreUsingSameKey" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(DataBufferTest.BEH_RepeatedlyStoreUsingSameKey PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(DataBufferTest.BEH_RandomAsync "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=DataBufferTest.BEH_RandomAsync" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(DataBufferTest.BEH_RandomAsync PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BufferValueParam/DataBufferValueParameterisedTest.BEH_Store/0 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=BufferValueParam/DataBufferValueParameterisedTest.BEH_Store/0" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BufferValueParam/DataBufferValueParameterisedTest.BEH_Store/0 PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BufferValueParam/DataBufferValueParameterisedTest.BEH_Store/1 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=BufferValueParam/DataBufferValueParameterisedTest.BEH_Store/1" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BufferValueParam/DataBufferValueParameterisedTest.BEH_Store/1 PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BufferValueParam/DataBufferValueParameterisedTest.BEH_Store/2 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=BufferValueParam/DataBufferValueParameterisedTest.BEH_Store/2" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BufferValueParam/DataBufferValueParameterisedTest.BEH_Store/2 PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BufferValueParam/DataBufferValueParameterisedTest.BEH_Store/3 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=BufferValueParam/DataBufferValueParameterisedTest.BEH_Store/3" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BufferValueParam/DataBufferValueParameterisedTest.BEH_Store/3 PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BufferValueParam/DataBufferValueParameterisedTest.BEH_Store/4 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=BufferValueParam/DataBufferValueParameterisedTest.BEH_Store/4" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BufferValueParam/DataBufferValueParameterisedTest.BEH_Store/4 PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BufferValueParam/DataBufferValueParameterisedTest.BEH_Store/5 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=BufferValueParam/DataBufferValueParameterisedTest.BEH_Store/5" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BufferValueParam/DataBufferValueParameterisedTest.BEH_Store/5 PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BufferValueParam/DataBufferValueParameterisedTest.BEH_Store/6 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=BufferValueParam/DataBufferValueParameterisedTest.BEH_Store/6" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BufferValueParam/DataBufferValueParameterisedTest.BEH_Store/6 PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BufferValueParam/DataBufferValueParameterisedTest.BEH_Store/7 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=BufferValueParam/DataBufferValueParameterisedTest.BEH_Store/7" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BufferValueParam/DataBufferValueParameterisedTest.BEH_Store/7 PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BufferValueParam/DataBufferValueParameterisedTest.BEH_Store/8 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=BufferValueParam/DataBufferValueParameterisedTest.BEH_Store/8" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BufferValueParam/DataBufferValueParameterisedTest.BEH_Store/8 PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BufferValueParam/DataBufferValueParameterisedTest.BEH_Delete/0 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=BufferValueParam/DataBufferValueParameterisedTest.BEH_Delete/0" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BufferValueParam/DataBufferValueParameterisedTest.BEH_Delete/0 PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BufferValueParam/DataBufferValueParameterisedTest.BEH_Delete/1 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=BufferValueParam/DataBufferValueParameterisedTest.BEH_Delete/1" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BufferValueParam/DataBufferValueParameterisedTest.BEH_Delete/1 PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BufferValueParam/DataBufferValueParameterisedTest.BEH_Delete/2 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=BufferValueParam/DataBufferValueParameterisedTest.BEH_Delete/2" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BufferValueParam/DataBufferValueParameterisedTest.BEH_Delete/2 PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BufferValueParam/DataBufferValueParameterisedTest.BEH_Delete/3 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=BufferValueParam/DataBufferValueParameterisedTest.BEH_Delete/3" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BufferValueParam/DataBufferValueParameterisedTest.BEH_Delete/3 PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BufferValueParam/DataBufferValueParameterisedTest.BEH_Delete/4 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=BufferValueParam/DataBufferValueParameterisedTest.BEH_Delete/4" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BufferValueParam/DataBufferValueParameterisedTest.BEH_Delete/4 PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BufferValueParam/DataBufferValueParameterisedTest.BEH_Delete/5 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=BufferValueParam/DataBufferValueParameterisedTest.BEH_Delete/5" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BufferValueParam/DataBufferValueParameterisedTest.BEH_Delete/5 PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BufferValueParam/DataBufferValueParameterisedTest.BEH_Delete/6 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=BufferValueParam/DataBufferValueParameterisedTest.BEH_Delete/6" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BufferValueParam/DataBufferValueParameterisedTest.BEH_Delete/6 PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BufferValueParam/DataBufferValueParameterisedTest.BEH_Delete/7 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=BufferValueParam/DataBufferValueParameterisedTest.BEH_Delete/7" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BufferValueParam/DataBufferValueParameterisedTest.BEH_Delete/7 PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BufferValueParam/DataBufferValueParameterisedTest.BEH_Delete/8 "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=BufferValueParam/DataBufferValueParameterisedTest.BEH_Delete/8" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BufferValueParam/DataBufferValueParameterisedTest.BEH_Delete/8 PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(DataBufferUnitTest.BEH_ZeroSizeMemory "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=DataBufferUnitTest.BEH_ZeroSizeMemory" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(DataBufferUnitTest.BEH_ZeroSizeMemory PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(DataBufferUnitTest.BEH_MaxMemoryLessMaxDiskUsage "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=DataBufferUnitTest.BEH_MaxMemoryLessMaxDiskUsage" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(DataBufferUnitTest.BEH_MaxMemoryLessMaxDiskUsage PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(DataBufferUnitTest.BEH_ZeroSizeDiskAndMemory "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=DataBufferUnitTest.BEH_ZeroSizeDiskAndMemory" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(DataBufferUnitTest.BEH_ZeroSizeDiskAndMemory PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(DataBufferUnitTest.BEH_ConstructWithComplexKey "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=DataBufferUnitTest.BEH_ConstructWithComplexKey" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(DataBufferUnitTest.BEH_ConstructWithComplexKey PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(DataBufferUnitTest.BEH_DiskOnlyInsertAndDelete "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=DataBufferUnitTest.BEH_DiskOnlyInsertAndDelete" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(DataBufferUnitTest.BEH_DiskOnlyInsertAndDelete PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(DataBufferUnitTest.BEH_DiskOnlyInsertAndDeleteComplexKey "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=DataBufferUnitTest.BEH_DiskOnlyInsertAndDeleteComplexKey" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(DataBufferUnitTest.BEH_DiskOnlyInsertAndDeleteComplexKey PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(DataBufferUnitTest.BEH_DiskOnlyInsertAndDeleteRange "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=DataBufferUnitTest.BEH_DiskOnlyInsertAndDeleteRange" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(DataBufferUnitTest.BEH_DiskOnlyInsertAndDeleteRange PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(ErrorsTest.BEH_ErrorCodeErrorCondition "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=ErrorsTest.BEH_ErrorCodeErrorCondition" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(ErrorsTest.BEH_ErrorCodeErrorCondition PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(ErrorsTest.BEH_ErrorCodesThrownAsBoostExceptions "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=ErrorsTest.BEH_ErrorCodesThrownAsBoostExceptions" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(ErrorsTest.BEH_ErrorCodesThrownAsBoostExceptions PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(ErrorsTest.BEH_SerialisingAndParsingErrors "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=ErrorsTest.BEH_SerialisingAndParsingErrors" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(ErrorsTest.BEH_SerialisingAndParsingErrors PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(MaidSafeErrorTest/0.BEH_ConstructorsAndHelpers "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=MaidSafeErrorTest/0.BEH_ConstructorsAndHelpers" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(MaidSafeErrorTest/0.BEH_ConstructorsAndHelpers PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(MaidSafeErrorTest/1.BEH_ConstructorsAndHelpers "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=MaidSafeErrorTest/1.BEH_ConstructorsAndHelpers" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(MaidSafeErrorTest/1.BEH_ConstructorsAndHelpers PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(MaidSafeErrorTest/2.BEH_ConstructorsAndHelpers "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=MaidSafeErrorTest/2.BEH_ConstructorsAndHelpers" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(MaidSafeErrorTest/2.BEH_ConstructorsAndHelpers PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(MaidSafeErrorTest/3.BEH_ConstructorsAndHelpers "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=MaidSafeErrorTest/3.BEH_ConstructorsAndHelpers" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(MaidSafeErrorTest/3.BEH_ConstructorsAndHelpers PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(MaidSafeErrorTest/4.BEH_ConstructorsAndHelpers "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=MaidSafeErrorTest/4.BEH_ConstructorsAndHelpers" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(MaidSafeErrorTest/4.BEH_ConstructorsAndHelpers PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(MaidSafeErrorTest/5.BEH_ConstructorsAndHelpers "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=MaidSafeErrorTest/5.BEH_ConstructorsAndHelpers" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(MaidSafeErrorTest/5.BEH_ConstructorsAndHelpers PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(MaidSafeErrorTest/6.BEH_ConstructorsAndHelpers "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=MaidSafeErrorTest/6.BEH_ConstructorsAndHelpers" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(MaidSafeErrorTest/6.BEH_ConstructorsAndHelpers PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(MaidSafeErrorTest/7.BEH_ConstructorsAndHelpers "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=MaidSafeErrorTest/7.BEH_ConstructorsAndHelpers" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(MaidSafeErrorTest/7.BEH_ConstructorsAndHelpers PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(MaidSafeErrorTest/8.BEH_ConstructorsAndHelpers "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=MaidSafeErrorTest/8.BEH_ConstructorsAndHelpers" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(MaidSafeErrorTest/8.BEH_ConstructorsAndHelpers PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(MaidSafeErrorTest/9.BEH_ConstructorsAndHelpers "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=MaidSafeErrorTest/9.BEH_ConstructorsAndHelpers" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(MaidSafeErrorTest/9.BEH_ConstructorsAndHelpers PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(MaidSafeErrorTest/10.BEH_ConstructorsAndHelpers "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=MaidSafeErrorTest/10.BEH_ConstructorsAndHelpers" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(MaidSafeErrorTest/10.BEH_ConstructorsAndHelpers PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(IpcTest.BEH_IpcCreate "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=IpcTest.BEH_IpcCreate" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(IpcTest.BEH_IpcCreate PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(IpcTest.BEH_IpcRead "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=IpcTest.BEH_IpcRead" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(IpcTest.BEH_IpcRead PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(IpcTest.BEH_IpcDelete "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=IpcTest.BEH_IpcDelete" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(IpcTest.BEH_IpcDelete PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(IpcTest.FUNC_IpcFunctionsThreaded "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=IpcTest.FUNC_IpcFunctionsThreaded" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(IpcTest.FUNC_IpcFunctionsThreaded PROPERTIES  LABELS "Common;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(IpcTest.FUNC_IpcFunctionsUsingBoostProcess "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=IpcTest.FUNC_IpcFunctionsUsingBoostProcess" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(IpcTest.FUNC_IpcFunctionsUsingBoostProcess PROPERTIES  LABELS "Common;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(MakeUniqueTest.BEH_MakeUnique "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=MakeUniqueTest.BEH_MakeUnique" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(MakeUniqueTest.BEH_MakeUnique PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(NodeIdBasicTest.BEH_DefaultConstructor "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=NodeIdBasicTest.BEH_DefaultConstructor" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(NodeIdBasicTest.BEH_DefaultConstructor PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(NodeIdBasicTest.BEH_CopyAndMove "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=NodeIdBasicTest.BEH_CopyAndMove" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(NodeIdBasicTest.BEH_CopyAndMove PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(NodeIdBasicTest.BEH_StringConstructor "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=NodeIdBasicTest.BEH_StringConstructor" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(NodeIdBasicTest.BEH_StringConstructor PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(NodeIdBasicTest.BEH_HashConstructor "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=NodeIdBasicTest.BEH_HashConstructor" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(NodeIdBasicTest.BEH_HashConstructor PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(NodeIdBasicTest.BEH_EncodingConstructor "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=NodeIdBasicTest.BEH_EncodingConstructor" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(NodeIdBasicTest.BEH_EncodingConstructor PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(NodeIdBasicTest.BEH_String "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=NodeIdBasicTest.BEH_String" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(NodeIdBasicTest.BEH_String PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(NodeIdBasicTest.BEH_IsValid "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=NodeIdBasicTest.BEH_IsValid" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(NodeIdBasicTest.BEH_IsValid PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(NodeIdTest.BEH_Operators "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=NodeIdTest.BEH_Operators" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(NodeIdTest.BEH_Operators PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(NodeIdTest.BEH_CloserToTarget "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=NodeIdTest.BEH_CloserToTarget" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(NodeIdTest.BEH_CloserToTarget PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(NodeIdTest.FUNC_CloserToTarget "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=NodeIdTest.FUNC_CloserToTarget" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(NodeIdTest.FUNC_CloserToTarget PROPERTIES  LABELS "Common;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(NodeIdTest.BEH_CommonLeadingBits "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=NodeIdTest.BEH_CommonLeadingBits" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(NodeIdTest.BEH_CommonLeadingBits PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(NodeIdTest.BEH_Serialisation "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=NodeIdTest.BEH_Serialisation" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(NodeIdTest.BEH_Serialisation PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(NodeIdTest.BEH_DebugId "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=NodeIdTest.BEH_DebugId" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(NodeIdTest.BEH_DebugId PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(NodeIdTest.BEH_Swap "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=NodeIdTest.BEH_Swap" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(NodeIdTest.BEH_Swap PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(OnScopeExitTest.BEH_RevertValue "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=OnScopeExitTest.BEH_RevertValue" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(OnScopeExitTest.BEH_RevertValue PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(OnScopeExitTest.BEH_SetAction "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=OnScopeExitTest.BEH_SetAction" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(OnScopeExitTest.BEH_SetAction PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(RsaTest.BEH_ValidateKey "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=RsaTest.BEH_ValidateKey" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(RsaTest.BEH_ValidateKey PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(RsaTest.BEH_RsaEncodeKeys "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=RsaTest.BEH_RsaEncodeKeys" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(RsaTest.BEH_RsaEncodeKeys PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(RsaTest.BEH_AsymEncryptDecrypt "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=RsaTest.BEH_AsymEncryptDecrypt" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(RsaTest.BEH_AsymEncryptDecrypt PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(RsaTest.FUNC_SignValidate "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=RsaTest.FUNC_SignValidate" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(RsaTest.FUNC_SignValidate PROPERTIES  LABELS "Common;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(RsaTest.FUNC_SignFileValidate "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=RsaTest.FUNC_SignFileValidate" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(RsaTest.FUNC_SignFileValidate PROPERTIES  LABELS "Common;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(RsaTest.BEH_RsaKeysComparing "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=RsaTest.BEH_RsaKeysComparing" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(RsaTest.BEH_RsaKeysComparing PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(RsaTest.BEH_SignatureSize "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=RsaTest.BEH_SignatureSize" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(RsaTest.BEH_SignatureSize PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(Sqlite3WrapperTest.FUNC_ReadInvalidDataBase "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=Sqlite3WrapperTest.FUNC_ReadInvalidDataBase" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Sqlite3WrapperTest.FUNC_ReadInvalidDataBase PROPERTIES  LABELS "Common;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(Sqlite3WrapperTest.FUNC_WriteEmptDataBase "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=Sqlite3WrapperTest.FUNC_WriteEmptDataBase" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Sqlite3WrapperTest.FUNC_WriteEmptDataBase PROPERTIES  LABELS "Common;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(Sqlite3WrapperTest.FUNC_WriteNewDataBase "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=Sqlite3WrapperTest.FUNC_WriteNewDataBase" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Sqlite3WrapperTest.FUNC_WriteNewDataBase PROPERTIES  LABELS "Common;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(Sqlite3WrapperTest.FUNC_WriteExistingDataBase "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=Sqlite3WrapperTest.FUNC_WriteExistingDataBase" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Sqlite3WrapperTest.FUNC_WriteExistingDataBase PROPERTIES  LABELS "Common;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(Sqlite3WrapperTest.FUNC_WriteRead "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=Sqlite3WrapperTest.FUNC_WriteRead" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(Sqlite3WrapperTest.FUNC_WriteRead PROPERTIES  LABELS "Common;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(UtilsTest.BEH_VersionInfo "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=UtilsTest.BEH_VersionInfo" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(UtilsTest.BEH_VersionInfo PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(UtilsTest.BEH_Names "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=UtilsTest.BEH_Names" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(UtilsTest.BEH_Names PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(UtilsTest.BEH_Ratios "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=UtilsTest.BEH_Ratios" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(UtilsTest.BEH_Ratios PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(UtilsTest.BEH_BytesToDecimalSiUnits "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=UtilsTest.BEH_BytesToDecimalSiUnits" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(UtilsTest.BEH_BytesToDecimalSiUnits PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(UtilsTest.BEH_BytesToBinarySiUnits "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=UtilsTest.BEH_BytesToBinarySiUnits" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(UtilsTest.BEH_BytesToBinarySiUnits PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(UtilsTest.FUNC_RandomStringMultiThread "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=UtilsTest.FUNC_RandomStringMultiThread" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(UtilsTest.FUNC_RandomStringMultiThread PROPERTIES  LABELS "Common;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(UtilsTest.BEH_RandomStringGenerator "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=UtilsTest.BEH_RandomStringGenerator" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(UtilsTest.BEH_RandomStringGenerator PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(UtilsTest.BEH_RandomStringSingleThread "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=UtilsTest.BEH_RandomStringSingleThread" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(UtilsTest.BEH_RandomStringSingleThread PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(UtilsTest.BEH_HexEncodeDecode "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=UtilsTest.BEH_HexEncodeDecode" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(UtilsTest.BEH_HexEncodeDecode PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(UtilsTest.BEH_Base64EncodeDecode "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=UtilsTest.BEH_Base64EncodeDecode" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(UtilsTest.BEH_Base64EncodeDecode PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(UtilsTest.BEH_HexSubstr "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=UtilsTest.BEH_HexSubstr" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(UtilsTest.BEH_HexSubstr PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(UtilsTest.BEH_Base64Substr "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=UtilsTest.BEH_Base64Substr" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(UtilsTest.BEH_Base64Substr PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(UtilsTest.BEH_WstringToString "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=UtilsTest.BEH_WstringToString" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(UtilsTest.BEH_WstringToString PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(UtilsTest.BEH_StringToWstring "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=UtilsTest.BEH_StringToWstring" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(UtilsTest.BEH_StringToWstring PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(UtilsTest.BEH_TimeFunctions "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=UtilsTest.BEH_TimeFunctions" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(UtilsTest.BEH_TimeFunctions PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(UtilsTest.FUNC_RandomNumberGen "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=UtilsTest.FUNC_RandomNumberGen" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(UtilsTest.FUNC_RandomNumberGen PROPERTIES  LABELS "Common;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(UtilsTest.BEH_ReadFileandWriteFile "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=UtilsTest.BEH_ReadFileandWriteFile" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(UtilsTest.BEH_ReadFileandWriteFile PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(UtilsTest.BEH_Sleep "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=UtilsTest.BEH_Sleep" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(UtilsTest.BEH_Sleep PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(UtilsTest.BEH_GetHomeDir "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=UtilsTest.BEH_GetHomeDir" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(UtilsTest.BEH_GetHomeDir PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(UtilsTest.BEH_GetUserAppDir "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=UtilsTest.BEH_GetUserAppDir" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(UtilsTest.BEH_GetUserAppDir PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(UtilsTest.BEH_GetSystemAppSupportDir "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=UtilsTest.BEH_GetSystemAppSupportDir" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(UtilsTest.BEH_GetSystemAppSupportDir PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(UtilsTest.BEH_GetAppInstallDir "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=UtilsTest.BEH_GetAppInstallDir" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(UtilsTest.BEH_GetAppInstallDir PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(UtilsTest.BEH_AppDir "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=UtilsTest.BEH_AppDir" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(UtilsTest.BEH_AppDir PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(UtilsTest.BEH_Concurrency "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=UtilsTest.BEH_Concurrency" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(UtilsTest.BEH_Concurrency PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(UtilsTest.BEH_CreateTestPath "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=UtilsTest.BEH_CreateTestPath" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(UtilsTest.BEH_CreateTestPath PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(UtilsTest.BEH_GetProcessId "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=UtilsTest.BEH_GetProcessId" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(UtilsTest.BEH_GetProcessId PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(SecureStringTest.BEH_Construct "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=SecureStringTest.BEH_Construct" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(SecureStringTest.BEH_Construct PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(SecureStringTest.BEH_Hash "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=SecureStringTest.BEH_Hash" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(SecureStringTest.BEH_Hash PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(SecureStringTest.BEH_CreatePassword "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=SecureStringTest.BEH_CreatePassword" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(SecureStringTest.BEH_CreatePassword PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(SecureStringTest.BEH_CreatePasswordString "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=SecureStringTest.BEH_CreatePasswordString" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(SecureStringTest.BEH_CreatePasswordString PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(SecureStringTest.BEH_PassEmptyPasswordString "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=SecureStringTest.BEH_PassEmptyPasswordString" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(SecureStringTest.BEH_PassEmptyPasswordString PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(SecureStringTest.BEH_RemoveFirstPasswordCharacter "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=SecureStringTest.BEH_RemoveFirstPasswordCharacter" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(SecureStringTest.BEH_RemoveFirstPasswordCharacter PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(SecureStringTest.BEH_RemoveLastPasswordCharacter "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=SecureStringTest.BEH_RemoveLastPasswordCharacter" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(SecureStringTest.BEH_RemoveLastPasswordCharacter PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(SecureStringTest.BEH_InsertAndRemoveAfterPasswordFinalised "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=SecureStringTest.BEH_InsertAndRemoveAfterPasswordFinalised" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(SecureStringTest.BEH_InsertAndRemoveAfterPasswordFinalised PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(SecureStringTest.BEH_CreatePasswordWithMissingIndex "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=SecureStringTest.BEH_CreatePasswordWithMissingIndex" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(SecureStringTest.BEH_CreatePasswordWithMissingIndex PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(SecureStringTest.BEH_CreateInvalidLengthPassword "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=SecureStringTest.BEH_CreateInvalidLengthPassword" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(SecureStringTest.BEH_CreateInvalidLengthPassword PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(SecureStringTest.BEH_ClearPasswordThenRedo "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=SecureStringTest.BEH_ClearPasswordThenRedo" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(SecureStringTest.BEH_ClearPasswordThenRedo PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(SecureStringTest.BEH_ClearPasswordAfterFinalised "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=SecureStringTest.BEH_ClearPasswordAfterFinalised" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(SecureStringTest.BEH_ClearPasswordAfterFinalised PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(SecureStringTest.BEH_GetPasswordTextBeforeFinalised "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=SecureStringTest.BEH_GetPasswordTextBeforeFinalised" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(SecureStringTest.BEH_GetPasswordTextBeforeFinalised PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(SecureStringTest.BEH_CheckPasswordIsValidForAllChars "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=SecureStringTest.BEH_CheckPasswordIsValidForAllChars" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(SecureStringTest.BEH_CheckPasswordIsValidForAllChars PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(SecureStringTest.BEH_CreatePin "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=SecureStringTest.BEH_CreatePin" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(SecureStringTest.BEH_CreatePin PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(SecureStringTest.BEH_CreateInvalidLengthPin "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=SecureStringTest.BEH_CreateInvalidLengthPin" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(SecureStringTest.BEH_CreateInvalidLengthPin PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(SecureStringTest.BEH_InsertInvalidPinValue "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=SecureStringTest.BEH_InsertInvalidPinValue" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(SecureStringTest.BEH_InsertInvalidPinValue PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(UserCredentialsTest.BEH_CreateSecurePassword "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=UserCredentialsTest.BEH_CreateSecurePassword" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(UserCredentialsTest.BEH_CreateSecurePassword PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(UserCredentialsTest.FUNC_ObfuscateData "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=UserCredentialsTest.FUNC_ObfuscateData" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(UserCredentialsTest.FUNC_ObfuscateData PROPERTIES  LABELS "Common;Functional" SKIP_RETURN_CODE "127" TIMEOUT "600")
add_test(UserCredentialsTest.BEH_DeriveSymmetricEncryptionKeyAndIv "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=UserCredentialsTest.BEH_DeriveSymmetricEncryptionKeyAndIv" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(UserCredentialsTest.BEH_DeriveSymmetricEncryptionKeyAndIv PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(TcpTest.BEH_Basic "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=TcpTest.BEH_Basic" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(TcpTest.BEH_Basic PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(TcpTest.BEH_UnavailablePort "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=TcpTest.BEH_UnavailablePort" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(TcpTest.BEH_UnavailablePort PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(TcpTest.BEH_InvalidMessageSizes "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=TcpTest.BEH_InvalidMessageSizes" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(TcpTest.BEH_InvalidMessageSizes PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(TcpTest.BEH_ServerConnectionAborts "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=TcpTest.BEH_ServerConnectionAborts" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(TcpTest.BEH_ServerConnectionAborts PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(TcpTest.BEH_ClientConnectionAborts "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=TcpTest.BEH_ClientConnectionAborts" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(TcpTest.BEH_ClientConnectionAborts PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(TcpTest.BEH_MultipleConnectionsToServer "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=TcpTest.BEH_MultipleConnectionsToServer" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(TcpTest.BEH_MultipleConnectionsToServer PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(LruCacheTest.BEH_SizeOnlyTest "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=LruCacheTest.BEH_SizeOnlyTest" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(LruCacheTest.BEH_SizeOnlyTest PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(LruCacheTest.BEH_DeleteTest "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=LruCacheTest.BEH_DeleteTest" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(LruCacheTest.BEH_DeleteTest PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(LruCacheTest.BEH_TimeOnlyTest "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=LruCacheTest.BEH_TimeOnlyTest" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(LruCacheTest.BEH_TimeOnlyTest PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(LruCacheTest.BEH_TimeAndSizeTest "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=LruCacheTest.BEH_TimeAndSizeTest" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(LruCacheTest.BEH_TimeAndSizeTest PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(LruCacheTest.BEH_FilterTimeAndSizeTest "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=LruCacheTest.BEH_FilterTimeAndSizeTest" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(LruCacheTest.BEH_FilterTimeAndSizeTest PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(LruCacheTest.BEH_TimeAndSizeStructValueTest "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=LruCacheTest.BEH_TimeAndSizeStructValueTest" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(LruCacheTest.BEH_TimeAndSizeStructValueTest PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(DataTypeTests.BEH_OutputOperator "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=DataTypeTests.BEH_OutputOperator" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(DataTypeTests.BEH_OutputOperator PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(DataTypeTests.BEH_ConstructType "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=DataTypeTests.BEH_ConstructType" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(DataTypeTests.BEH_ConstructType PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(DataTypeTests.BEH_RetrieveType "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=DataTypeTests.BEH_RetrieveType" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(DataTypeTests.BEH_RetrieveType PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(MutableDataTest.BEH_Serialisation "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=MutableDataTest.BEH_Serialisation" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(MutableDataTest.BEH_Serialisation PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(StructuredDataVersionsTests.BEH_Put "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=StructuredDataVersionsTests.BEH_Put" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(StructuredDataVersionsTests.BEH_Put PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(StructuredDataVersionsTests.BEH_PutOrphans "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=StructuredDataVersionsTests.BEH_PutOrphans" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(StructuredDataVersionsTests.BEH_PutOrphans PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(StructuredDataVersionsTests.BEH_Serialise "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=StructuredDataVersionsTests.BEH_Serialise" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(StructuredDataVersionsTests.BEH_Serialise PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(StructuredDataVersionsTests.BEH_ApplySerialised "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=StructuredDataVersionsTests.BEH_ApplySerialised" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(StructuredDataVersionsTests.BEH_ApplySerialised PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(StructuredDataVersionsTests.BEH_SerialisationOptionalFieldTest "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=StructuredDataVersionsTests.BEH_SerialisationOptionalFieldTest" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(StructuredDataVersionsTests.BEH_SerialisationOptionalFieldTest PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BinaryArchiveTest.BEH_Basic "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common" "--gtest_filter=BinaryArchiveTest.BEH_Basic" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BinaryArchiveTest.BEH_Basic PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(NetworkViewerTest.BEH_MatrixRecordSerialisation "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_network_viewer" "--gtest_filter=NetworkViewerTest.BEH_MatrixRecordSerialisation" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(NetworkViewerTest.BEH_MatrixRecordSerialisation PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(BootstrapFileToolTest.BEH_Serialisation "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_bootstrap_file_tool" "--gtest_filter=BootstrapFileToolTest.BEH_Serialisation" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(BootstrapFileToolTest.BEH_Serialisation PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(ConfigTest.BEH_ApplicationVersion "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common_config" "--gtest_filter=ConfigTest.BEH_ApplicationVersion" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(ConfigTest.BEH_ApplicationVersion PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(ConfigTest.BEH_TargetPlatform "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common_config" "--gtest_filter=ConfigTest.BEH_TargetPlatform" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(ConfigTest.BEH_TargetPlatform PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(ConfigTest.BEH_TargetArchitecture "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common_config" "--gtest_filter=ConfigTest.BEH_TargetArchitecture" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(ConfigTest.BEH_TargetArchitecture PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
add_test(ConfigTest.BEH_ThisExecutableDir "/Users/Rafa/pocs/MaidSafeBuild/build_maidsafe/test_common_config" "--gtest_filter=ConfigTest.BEH_ThisExecutableDir" "--gtest_catch_exceptions=0" "" "")
set_tests_properties(ConfigTest.BEH_ThisExecutableDir PROPERTIES  LABELS "Common;Behavioural" SKIP_RETURN_CODE "127" TIMEOUT "60")
