// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: maidsafe/vault/version_handler/action_create_version_tree.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "maidsafe/vault/version_handler/action_create_version_tree.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
// @@protoc_insertion_point(includes)

namespace maidsafe {
namespace vault {
namespace protobuf {

void protobuf_ShutdownFile_maidsafe_2fvault_2fversion_5fhandler_2faction_5fcreate_5fversion_5ftree_2eproto() {
  delete ActionCreateVersionTree::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_maidsafe_2fvault_2fversion_5fhandler_2faction_5fcreate_5fversion_5ftree_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_maidsafe_2fvault_2fversion_5fhandler_2faction_5fcreate_5fversion_5ftree_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  ActionCreateVersionTree::default_instance_ = new ActionCreateVersionTree();
  ActionCreateVersionTree::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_maidsafe_2fvault_2fversion_5fhandler_2faction_5fcreate_5fversion_5ftree_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_maidsafe_2fvault_2fversion_5fhandler_2faction_5fcreate_5fversion_5ftree_2eproto_once_);
void protobuf_AddDesc_maidsafe_2fvault_2fversion_5fhandler_2faction_5fcreate_5fversion_5ftree_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_maidsafe_2fvault_2fversion_5fhandler_2faction_5fcreate_5fversion_5ftree_2eproto_once_,
                 &protobuf_AddDesc_maidsafe_2fvault_2fversion_5fhandler_2faction_5fcreate_5fversion_5ftree_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_maidsafe_2fvault_2fversion_5fhandler_2faction_5fcreate_5fversion_5ftree_2eproto {
  StaticDescriptorInitializer_maidsafe_2fvault_2fversion_5fhandler_2faction_5fcreate_5fversion_5ftree_2eproto() {
    protobuf_AddDesc_maidsafe_2fvault_2fversion_5fhandler_2faction_5fcreate_5fversion_5ftree_2eproto();
  }
} static_descriptor_initializer_maidsafe_2fvault_2fversion_5fhandler_2faction_5fcreate_5fversion_5ftree_2eproto_;
#endif

// ===================================================================

#ifndef _MSC_VER
const int ActionCreateVersionTree::kSerialisedVersionFieldNumber;
const int ActionCreateVersionTree::kMaxVersionsFieldNumber;
const int ActionCreateVersionTree::kMaxBranchesFieldNumber;
const int ActionCreateVersionTree::kMessageIdFieldNumber;
const int ActionCreateVersionTree::kOriginatorFieldNumber;
#endif  // !_MSC_VER

ActionCreateVersionTree::ActionCreateVersionTree()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void ActionCreateVersionTree::InitAsDefaultInstance() {
}

ActionCreateVersionTree::ActionCreateVersionTree(const ActionCreateVersionTree& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void ActionCreateVersionTree::SharedCtor() {
  _cached_size_ = 0;
  serialised_version_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyString());
  max_versions_ = 0;
  max_branches_ = 0;
  message_id_ = 0;
  originator_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyString());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ActionCreateVersionTree::~ActionCreateVersionTree() {
  SharedDtor();
}

void ActionCreateVersionTree::SharedDtor() {
  if (serialised_version_ != &::google::protobuf::internal::GetEmptyString()) {
    delete serialised_version_;
  }
  if (originator_ != &::google::protobuf::internal::GetEmptyString()) {
    delete originator_;
  }
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void ActionCreateVersionTree::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ActionCreateVersionTree& ActionCreateVersionTree::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_maidsafe_2fvault_2fversion_5fhandler_2faction_5fcreate_5fversion_5ftree_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_maidsafe_2fvault_2fversion_5fhandler_2faction_5fcreate_5fversion_5ftree_2eproto();
#endif
  return *default_instance_;
}

ActionCreateVersionTree* ActionCreateVersionTree::default_instance_ = NULL;

ActionCreateVersionTree* ActionCreateVersionTree::New() const {
  return new ActionCreateVersionTree;
}

void ActionCreateVersionTree::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_serialised_version()) {
      if (serialised_version_ != &::google::protobuf::internal::GetEmptyString()) {
        serialised_version_->clear();
      }
    }
    max_versions_ = 0;
    max_branches_ = 0;
    message_id_ = 0;
    if (has_originator()) {
      if (originator_ != &::google::protobuf::internal::GetEmptyString()) {
        originator_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool ActionCreateVersionTree::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bytes serialised_version = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_serialised_version()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_max_versions;
        break;
      }

      // required int32 max_versions = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_max_versions:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &max_versions_)));
          set_has_max_versions();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_max_branches;
        break;
      }

      // required int32 max_branches = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_max_branches:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &max_branches_)));
          set_has_max_branches();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_message_id;
        break;
      }

      // required int32 message_id = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_message_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &message_id_)));
          set_has_message_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(42)) goto parse_originator;
        break;
      }

      // required bytes originator = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_originator:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_originator()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ActionCreateVersionTree::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required bytes serialised_version = 1;
  if (has_serialised_version()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      1, this->serialised_version(), output);
  }

  // required int32 max_versions = 2;
  if (has_max_versions()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->max_versions(), output);
  }

  // required int32 max_branches = 3;
  if (has_max_branches()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->max_branches(), output);
  }

  // required int32 message_id = 4;
  if (has_message_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->message_id(), output);
  }

  // required bytes originator = 5;
  if (has_originator()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      5, this->originator(), output);
  }

}

int ActionCreateVersionTree::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required bytes serialised_version = 1;
    if (has_serialised_version()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->serialised_version());
    }

    // required int32 max_versions = 2;
    if (has_max_versions()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->max_versions());
    }

    // required int32 max_branches = 3;
    if (has_max_branches()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->max_branches());
    }

    // required int32 message_id = 4;
    if (has_message_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->message_id());
    }

    // required bytes originator = 5;
    if (has_originator()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->originator());
    }

  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ActionCreateVersionTree::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const ActionCreateVersionTree*>(&from));
}

void ActionCreateVersionTree::MergeFrom(const ActionCreateVersionTree& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_serialised_version()) {
      set_serialised_version(from.serialised_version());
    }
    if (from.has_max_versions()) {
      set_max_versions(from.max_versions());
    }
    if (from.has_max_branches()) {
      set_max_branches(from.max_branches());
    }
    if (from.has_message_id()) {
      set_message_id(from.message_id());
    }
    if (from.has_originator()) {
      set_originator(from.originator());
    }
  }
}

void ActionCreateVersionTree::CopyFrom(const ActionCreateVersionTree& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ActionCreateVersionTree::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000001f) != 0x0000001f) return false;

  return true;
}

void ActionCreateVersionTree::Swap(ActionCreateVersionTree* other) {
  if (other != this) {
    std::swap(serialised_version_, other->serialised_version_);
    std::swap(max_versions_, other->max_versions_);
    std::swap(max_branches_, other->max_branches_);
    std::swap(message_id_, other->message_id_);
    std::swap(originator_, other->originator_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string ActionCreateVersionTree::GetTypeName() const {
  return "maidsafe.vault.protobuf.ActionCreateVersionTree";
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace vault
}  // namespace maidsafe

// @@protoc_insertion_point(global_scope)
