// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: maidsafe/vault/maid_manager/action_put.proto

#ifndef PROTOBUF_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fput_2eproto__INCLUDED
#define PROTOBUF_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fput_2eproto__INCLUDED

#ifdef _MSC_VER
#  pragma warning(push)
#  pragma warning(disable: 4127 4244 4267)
#endif

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace maidsafe {
namespace vault {
namespace protobuf {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fput_2eproto();
void protobuf_AssignDesc_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fput_2eproto();
void protobuf_ShutdownFile_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fput_2eproto();

class ActionMaidManagerPut;

// ===================================================================

class ActionMaidManagerPut : public ::google::protobuf::MessageLite {
 public:
  ActionMaidManagerPut();
  virtual ~ActionMaidManagerPut();

  ActionMaidManagerPut(const ActionMaidManagerPut& from);

  inline ActionMaidManagerPut& operator=(const ActionMaidManagerPut& from) {
    CopyFrom(from);
    return *this;
  }

  static const ActionMaidManagerPut& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const ActionMaidManagerPut* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(ActionMaidManagerPut* other);

  // implements Message ----------------------------------------------

  ActionMaidManagerPut* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const ActionMaidManagerPut& from);
  void MergeFrom(const ActionMaidManagerPut& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 size = 1;
  inline bool has_size() const;
  inline void clear_size();
  static const int kSizeFieldNumber = 1;
  inline ::google::protobuf::int64 size() const;
  inline void set_size(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:maidsafe.vault.protobuf.ActionMaidManagerPut)
 private:
  inline void set_has_size();
  inline void clear_has_size();

  ::google::protobuf::int64 size_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fput_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fput_2eproto();
  #endif
  friend void protobuf_AssignDesc_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fput_2eproto();
  friend void protobuf_ShutdownFile_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fput_2eproto();

  void InitAsDefaultInstance();
  static ActionMaidManagerPut* default_instance_;
};
// ===================================================================


// ===================================================================

// ActionMaidManagerPut

// required int64 size = 1;
inline bool ActionMaidManagerPut::has_size() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ActionMaidManagerPut::set_has_size() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ActionMaidManagerPut::clear_has_size() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ActionMaidManagerPut::clear_size() {
  size_ = GOOGLE_LONGLONG(0);
  clear_has_size();
}
inline ::google::protobuf::int64 ActionMaidManagerPut::size() const {
  return size_;
}
inline void ActionMaidManagerPut::set_size(::google::protobuf::int64 value) {
  set_has_size();
  size_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace vault
}  // namespace maidsafe

// @@protoc_insertion_point(global_scope)

#ifdef _MSC_VER
#  pragma warning(pop)
#endif

#endif  // PROTOBUF_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fput_2eproto__INCLUDED
