// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: maidsafe/vault/maid_manager/action_put.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "maidsafe/vault/maid_manager/action_put.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
// @@protoc_insertion_point(includes)

namespace maidsafe {
namespace vault {
namespace protobuf {

void protobuf_ShutdownFile_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fput_2eproto() {
  delete ActionMaidManagerPut::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fput_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fput_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  ActionMaidManagerPut::default_instance_ = new ActionMaidManagerPut();
  ActionMaidManagerPut::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fput_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fput_2eproto_once_);
void protobuf_AddDesc_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fput_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fput_2eproto_once_,
                 &protobuf_AddDesc_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fput_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fput_2eproto {
  StaticDescriptorInitializer_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fput_2eproto() {
    protobuf_AddDesc_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fput_2eproto();
  }
} static_descriptor_initializer_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fput_2eproto_;
#endif

// ===================================================================

#ifndef _MSC_VER
const int ActionMaidManagerPut::kSizeFieldNumber;
#endif  // !_MSC_VER

ActionMaidManagerPut::ActionMaidManagerPut()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void ActionMaidManagerPut::InitAsDefaultInstance() {
}

ActionMaidManagerPut::ActionMaidManagerPut(const ActionMaidManagerPut& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void ActionMaidManagerPut::SharedCtor() {
  _cached_size_ = 0;
  size_ = GOOGLE_LONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ActionMaidManagerPut::~ActionMaidManagerPut() {
  SharedDtor();
}

void ActionMaidManagerPut::SharedDtor() {
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void ActionMaidManagerPut::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ActionMaidManagerPut& ActionMaidManagerPut::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fput_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fput_2eproto();
#endif
  return *default_instance_;
}

ActionMaidManagerPut* ActionMaidManagerPut::default_instance_ = NULL;

ActionMaidManagerPut* ActionMaidManagerPut::New() const {
  return new ActionMaidManagerPut;
}

void ActionMaidManagerPut::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    size_ = GOOGLE_LONGLONG(0);
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool ActionMaidManagerPut::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int64 size = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &size_)));
          set_has_size();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ActionMaidManagerPut::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int64 size = 1;
  if (has_size()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->size(), output);
  }

}

int ActionMaidManagerPut::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int64 size = 1;
    if (has_size()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->size());
    }

  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ActionMaidManagerPut::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const ActionMaidManagerPut*>(&from));
}

void ActionMaidManagerPut::MergeFrom(const ActionMaidManagerPut& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_size()) {
      set_size(from.size());
    }
  }
}

void ActionMaidManagerPut::CopyFrom(const ActionMaidManagerPut& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ActionMaidManagerPut::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void ActionMaidManagerPut::Swap(ActionMaidManagerPut* other) {
  if (other != this) {
    std::swap(size_, other->size_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string ActionMaidManagerPut::GetTypeName() const {
  return "maidsafe.vault.protobuf.ActionMaidManagerPut";
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace vault
}  // namespace maidsafe

// @@protoc_insertion_point(global_scope)
