// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: maidsafe/vault/maid_manager/action_create_remove_account.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "maidsafe/vault/maid_manager/action_create_remove_account.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
// @@protoc_insertion_point(includes)

namespace maidsafe {
namespace vault {
namespace protobuf {

void protobuf_ShutdownFile_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fcreate_5fremove_5faccount_2eproto() {
  delete ActionMaidManagerCreateRemoveAccount::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fcreate_5fremove_5faccount_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fcreate_5fremove_5faccount_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  ActionMaidManagerCreateRemoveAccount::default_instance_ = new ActionMaidManagerCreateRemoveAccount();
  ActionMaidManagerCreateRemoveAccount::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fcreate_5fremove_5faccount_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fcreate_5fremove_5faccount_2eproto_once_);
void protobuf_AddDesc_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fcreate_5fremove_5faccount_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fcreate_5fremove_5faccount_2eproto_once_,
                 &protobuf_AddDesc_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fcreate_5fremove_5faccount_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fcreate_5fremove_5faccount_2eproto {
  StaticDescriptorInitializer_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fcreate_5fremove_5faccount_2eproto() {
    protobuf_AddDesc_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fcreate_5fremove_5faccount_2eproto();
  }
} static_descriptor_initializer_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fcreate_5fremove_5faccount_2eproto_;
#endif

// ===================================================================

#ifndef _MSC_VER
const int ActionMaidManagerCreateRemoveAccount::kMessageIdFieldNumber;
#endif  // !_MSC_VER

ActionMaidManagerCreateRemoveAccount::ActionMaidManagerCreateRemoveAccount()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void ActionMaidManagerCreateRemoveAccount::InitAsDefaultInstance() {
}

ActionMaidManagerCreateRemoveAccount::ActionMaidManagerCreateRemoveAccount(const ActionMaidManagerCreateRemoveAccount& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void ActionMaidManagerCreateRemoveAccount::SharedCtor() {
  _cached_size_ = 0;
  message_id_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ActionMaidManagerCreateRemoveAccount::~ActionMaidManagerCreateRemoveAccount() {
  SharedDtor();
}

void ActionMaidManagerCreateRemoveAccount::SharedDtor() {
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void ActionMaidManagerCreateRemoveAccount::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ActionMaidManagerCreateRemoveAccount& ActionMaidManagerCreateRemoveAccount::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fcreate_5fremove_5faccount_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_maidsafe_2fvault_2fmaid_5fmanager_2faction_5fcreate_5fremove_5faccount_2eproto();
#endif
  return *default_instance_;
}

ActionMaidManagerCreateRemoveAccount* ActionMaidManagerCreateRemoveAccount::default_instance_ = NULL;

ActionMaidManagerCreateRemoveAccount* ActionMaidManagerCreateRemoveAccount::New() const {
  return new ActionMaidManagerCreateRemoveAccount;
}

void ActionMaidManagerCreateRemoveAccount::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    message_id_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool ActionMaidManagerCreateRemoveAccount::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 message_id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &message_id_)));
          set_has_message_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ActionMaidManagerCreateRemoveAccount::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 message_id = 1;
  if (has_message_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->message_id(), output);
  }

}

int ActionMaidManagerCreateRemoveAccount::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 message_id = 1;
    if (has_message_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->message_id());
    }

  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ActionMaidManagerCreateRemoveAccount::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const ActionMaidManagerCreateRemoveAccount*>(&from));
}

void ActionMaidManagerCreateRemoveAccount::MergeFrom(const ActionMaidManagerCreateRemoveAccount& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_message_id()) {
      set_message_id(from.message_id());
    }
  }
}

void ActionMaidManagerCreateRemoveAccount::CopyFrom(const ActionMaidManagerCreateRemoveAccount& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ActionMaidManagerCreateRemoveAccount::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void ActionMaidManagerCreateRemoveAccount::Swap(ActionMaidManagerCreateRemoveAccount* other) {
  if (other != this) {
    std::swap(message_id_, other->message_id_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string ActionMaidManagerCreateRemoveAccount::GetTypeName() const {
  return "maidsafe.vault.protobuf.ActionMaidManagerCreateRemoveAccount";
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace vault
}  // namespace maidsafe

// @@protoc_insertion_point(global_scope)
