// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: maidsafe/vault/pmid_manager/action_delete.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "maidsafe/vault/pmid_manager/action_delete.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
// @@protoc_insertion_point(includes)

namespace maidsafe {
namespace vault {
namespace protobuf {

void protobuf_ShutdownFile_maidsafe_2fvault_2fpmid_5fmanager_2faction_5fdelete_2eproto() {
  delete ActionPmidManagerDelete::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_maidsafe_2fvault_2fpmid_5fmanager_2faction_5fdelete_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_maidsafe_2fvault_2fpmid_5fmanager_2faction_5fdelete_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  ActionPmidManagerDelete::default_instance_ = new ActionPmidManagerDelete();
  ActionPmidManagerDelete::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_maidsafe_2fvault_2fpmid_5fmanager_2faction_5fdelete_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_maidsafe_2fvault_2fpmid_5fmanager_2faction_5fdelete_2eproto_once_);
void protobuf_AddDesc_maidsafe_2fvault_2fpmid_5fmanager_2faction_5fdelete_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_maidsafe_2fvault_2fpmid_5fmanager_2faction_5fdelete_2eproto_once_,
                 &protobuf_AddDesc_maidsafe_2fvault_2fpmid_5fmanager_2faction_5fdelete_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_maidsafe_2fvault_2fpmid_5fmanager_2faction_5fdelete_2eproto {
  StaticDescriptorInitializer_maidsafe_2fvault_2fpmid_5fmanager_2faction_5fdelete_2eproto() {
    protobuf_AddDesc_maidsafe_2fvault_2fpmid_5fmanager_2faction_5fdelete_2eproto();
  }
} static_descriptor_initializer_maidsafe_2fvault_2fpmid_5fmanager_2faction_5fdelete_2eproto_;
#endif

// ===================================================================

#ifndef _MSC_VER
const int ActionPmidManagerDelete::kSizeFieldNumber;
const int ActionPmidManagerDelete::kPmidNodeAvailableFieldNumber;
const int ActionPmidManagerDelete::kDataFailureFieldNumber;
#endif  // !_MSC_VER

ActionPmidManagerDelete::ActionPmidManagerDelete()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void ActionPmidManagerDelete::InitAsDefaultInstance() {
}

ActionPmidManagerDelete::ActionPmidManagerDelete(const ActionPmidManagerDelete& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void ActionPmidManagerDelete::SharedCtor() {
  _cached_size_ = 0;
  size_ = GOOGLE_ULONGLONG(0);
  pmid_node_available_ = false;
  data_failure_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ActionPmidManagerDelete::~ActionPmidManagerDelete() {
  SharedDtor();
}

void ActionPmidManagerDelete::SharedDtor() {
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void ActionPmidManagerDelete::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ActionPmidManagerDelete& ActionPmidManagerDelete::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_maidsafe_2fvault_2fpmid_5fmanager_2faction_5fdelete_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_maidsafe_2fvault_2fpmid_5fmanager_2faction_5fdelete_2eproto();
#endif
  return *default_instance_;
}

ActionPmidManagerDelete* ActionPmidManagerDelete::default_instance_ = NULL;

ActionPmidManagerDelete* ActionPmidManagerDelete::New() const {
  return new ActionPmidManagerDelete;
}

void ActionPmidManagerDelete::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    size_ = GOOGLE_ULONGLONG(0);
    pmid_node_available_ = false;
    data_failure_ = false;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool ActionPmidManagerDelete::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint64 size = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &size_)));
          set_has_size();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_pmid_node_available;
        break;
      }

      // required bool pmid_node_available = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_pmid_node_available:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &pmid_node_available_)));
          set_has_pmid_node_available();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_data_failure;
        break;
      }

      // required bool data_failure = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_data_failure:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &data_failure_)));
          set_has_data_failure();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ActionPmidManagerDelete::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint64 size = 1;
  if (has_size()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->size(), output);
  }

  // required bool pmid_node_available = 2;
  if (has_pmid_node_available()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->pmid_node_available(), output);
  }

  // required bool data_failure = 3;
  if (has_data_failure()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->data_failure(), output);
  }

}

int ActionPmidManagerDelete::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint64 size = 1;
    if (has_size()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->size());
    }

    // required bool pmid_node_available = 2;
    if (has_pmid_node_available()) {
      total_size += 1 + 1;
    }

    // required bool data_failure = 3;
    if (has_data_failure()) {
      total_size += 1 + 1;
    }

  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ActionPmidManagerDelete::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const ActionPmidManagerDelete*>(&from));
}

void ActionPmidManagerDelete::MergeFrom(const ActionPmidManagerDelete& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_size()) {
      set_size(from.size());
    }
    if (from.has_pmid_node_available()) {
      set_pmid_node_available(from.pmid_node_available());
    }
    if (from.has_data_failure()) {
      set_data_failure(from.data_failure());
    }
  }
}

void ActionPmidManagerDelete::CopyFrom(const ActionPmidManagerDelete& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ActionPmidManagerDelete::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void ActionPmidManagerDelete::Swap(ActionPmidManagerDelete* other) {
  if (other != this) {
    std::swap(size_, other->size_);
    std::swap(pmid_node_available_, other->pmid_node_available_);
    std::swap(data_failure_, other->data_failure_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string ActionPmidManagerDelete::GetTypeName() const {
  return "maidsafe.vault.protobuf.ActionPmidManagerDelete";
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace vault
}  // namespace maidsafe

// @@protoc_insertion_point(global_scope)
