// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: maidsafe/vault/pmid_manager/action_delete.proto

#ifndef PROTOBUF_maidsafe_2fvault_2fpmid_5fmanager_2faction_5fdelete_2eproto__INCLUDED
#define PROTOBUF_maidsafe_2fvault_2fpmid_5fmanager_2faction_5fdelete_2eproto__INCLUDED

#ifdef _MSC_VER
#  pragma warning(push)
#  pragma warning(disable: 4127 4244 4267)
#endif

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace maidsafe {
namespace vault {
namespace protobuf {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_maidsafe_2fvault_2fpmid_5fmanager_2faction_5fdelete_2eproto();
void protobuf_AssignDesc_maidsafe_2fvault_2fpmid_5fmanager_2faction_5fdelete_2eproto();
void protobuf_ShutdownFile_maidsafe_2fvault_2fpmid_5fmanager_2faction_5fdelete_2eproto();

class ActionPmidManagerDelete;

// ===================================================================

class ActionPmidManagerDelete : public ::google::protobuf::MessageLite {
 public:
  ActionPmidManagerDelete();
  virtual ~ActionPmidManagerDelete();

  ActionPmidManagerDelete(const ActionPmidManagerDelete& from);

  inline ActionPmidManagerDelete& operator=(const ActionPmidManagerDelete& from) {
    CopyFrom(from);
    return *this;
  }

  static const ActionPmidManagerDelete& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const ActionPmidManagerDelete* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(ActionPmidManagerDelete* other);

  // implements Message ----------------------------------------------

  ActionPmidManagerDelete* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const ActionPmidManagerDelete& from);
  void MergeFrom(const ActionPmidManagerDelete& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 size = 1;
  inline bool has_size() const;
  inline void clear_size();
  static const int kSizeFieldNumber = 1;
  inline ::google::protobuf::uint64 size() const;
  inline void set_size(::google::protobuf::uint64 value);

  // required bool pmid_node_available = 2;
  inline bool has_pmid_node_available() const;
  inline void clear_pmid_node_available();
  static const int kPmidNodeAvailableFieldNumber = 2;
  inline bool pmid_node_available() const;
  inline void set_pmid_node_available(bool value);

  // required bool data_failure = 3;
  inline bool has_data_failure() const;
  inline void clear_data_failure();
  static const int kDataFailureFieldNumber = 3;
  inline bool data_failure() const;
  inline void set_data_failure(bool value);

  // @@protoc_insertion_point(class_scope:maidsafe.vault.protobuf.ActionPmidManagerDelete)
 private:
  inline void set_has_size();
  inline void clear_has_size();
  inline void set_has_pmid_node_available();
  inline void clear_has_pmid_node_available();
  inline void set_has_data_failure();
  inline void clear_has_data_failure();

  ::google::protobuf::uint64 size_;
  bool pmid_node_available_;
  bool data_failure_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_maidsafe_2fvault_2fpmid_5fmanager_2faction_5fdelete_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_maidsafe_2fvault_2fpmid_5fmanager_2faction_5fdelete_2eproto();
  #endif
  friend void protobuf_AssignDesc_maidsafe_2fvault_2fpmid_5fmanager_2faction_5fdelete_2eproto();
  friend void protobuf_ShutdownFile_maidsafe_2fvault_2fpmid_5fmanager_2faction_5fdelete_2eproto();

  void InitAsDefaultInstance();
  static ActionPmidManagerDelete* default_instance_;
};
// ===================================================================


// ===================================================================

// ActionPmidManagerDelete

// required uint64 size = 1;
inline bool ActionPmidManagerDelete::has_size() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ActionPmidManagerDelete::set_has_size() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ActionPmidManagerDelete::clear_has_size() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ActionPmidManagerDelete::clear_size() {
  size_ = GOOGLE_ULONGLONG(0);
  clear_has_size();
}
inline ::google::protobuf::uint64 ActionPmidManagerDelete::size() const {
  return size_;
}
inline void ActionPmidManagerDelete::set_size(::google::protobuf::uint64 value) {
  set_has_size();
  size_ = value;
}

// required bool pmid_node_available = 2;
inline bool ActionPmidManagerDelete::has_pmid_node_available() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ActionPmidManagerDelete::set_has_pmid_node_available() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ActionPmidManagerDelete::clear_has_pmid_node_available() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ActionPmidManagerDelete::clear_pmid_node_available() {
  pmid_node_available_ = false;
  clear_has_pmid_node_available();
}
inline bool ActionPmidManagerDelete::pmid_node_available() const {
  return pmid_node_available_;
}
inline void ActionPmidManagerDelete::set_pmid_node_available(bool value) {
  set_has_pmid_node_available();
  pmid_node_available_ = value;
}

// required bool data_failure = 3;
inline bool ActionPmidManagerDelete::has_data_failure() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ActionPmidManagerDelete::set_has_data_failure() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ActionPmidManagerDelete::clear_has_data_failure() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ActionPmidManagerDelete::clear_data_failure() {
  data_failure_ = false;
  clear_has_data_failure();
}
inline bool ActionPmidManagerDelete::data_failure() const {
  return data_failure_;
}
inline void ActionPmidManagerDelete::set_data_failure(bool value) {
  set_has_data_failure();
  data_failure_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace vault
}  // namespace maidsafe

// @@protoc_insertion_point(global_scope)

#ifdef _MSC_VER
#  pragma warning(pop)
#endif

#endif  // PROTOBUF_maidsafe_2fvault_2fpmid_5fmanager_2faction_5fdelete_2eproto__INCLUDED
