// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: maidsafe/nfs/vault/account_removal.proto

#ifndef PROTOBUF_maidsafe_2fnfs_2fvault_2faccount_5fremoval_2eproto__INCLUDED
#define PROTOBUF_maidsafe_2fnfs_2fvault_2faccount_5fremoval_2eproto__INCLUDED

#ifdef _MSC_VER
#  pragma warning(push)
#  pragma warning(disable: 4127 4244 4267)
#endif

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace maidsafe {
namespace nfs_vault {
namespace protobuf {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_maidsafe_2fnfs_2fvault_2faccount_5fremoval_2eproto();
void protobuf_AssignDesc_maidsafe_2fnfs_2fvault_2faccount_5fremoval_2eproto();
void protobuf_ShutdownFile_maidsafe_2fnfs_2fvault_2faccount_5fremoval_2eproto();

class AccountRemoval;

// ===================================================================

class AccountRemoval : public ::google::protobuf::MessageLite {
 public:
  AccountRemoval();
  virtual ~AccountRemoval();

  AccountRemoval(const AccountRemoval& from);

  inline AccountRemoval& operator=(const AccountRemoval& from) {
    CopyFrom(from);
    return *this;
  }

  static const AccountRemoval& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const AccountRemoval* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(AccountRemoval* other);

  // implements Message ----------------------------------------------

  AccountRemoval* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const AccountRemoval& from);
  void MergeFrom(const AccountRemoval& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bytes random_data = 1;
  inline bool has_random_data() const;
  inline void clear_random_data();
  static const int kRandomDataFieldNumber = 1;
  inline const ::std::string& random_data() const;
  inline void set_random_data(const ::std::string& value);
  inline void set_random_data(const char* value);
  inline void set_random_data(const void* value, size_t size);
  inline ::std::string* mutable_random_data();
  inline ::std::string* release_random_data();
  inline void set_allocated_random_data(::std::string* random_data);

  // required bytes public_anmaid_name = 2;
  inline bool has_public_anmaid_name() const;
  inline void clear_public_anmaid_name();
  static const int kPublicAnmaidNameFieldNumber = 2;
  inline const ::std::string& public_anmaid_name() const;
  inline void set_public_anmaid_name(const ::std::string& value);
  inline void set_public_anmaid_name(const char* value);
  inline void set_public_anmaid_name(const void* value, size_t size);
  inline ::std::string* mutable_public_anmaid_name();
  inline ::std::string* release_public_anmaid_name();
  inline void set_allocated_public_anmaid_name(::std::string* public_anmaid_name);

  // required bytes signature = 3;
  inline bool has_signature() const;
  inline void clear_signature();
  static const int kSignatureFieldNumber = 3;
  inline const ::std::string& signature() const;
  inline void set_signature(const ::std::string& value);
  inline void set_signature(const char* value);
  inline void set_signature(const void* value, size_t size);
  inline ::std::string* mutable_signature();
  inline ::std::string* release_signature();
  inline void set_allocated_signature(::std::string* signature);

  // @@protoc_insertion_point(class_scope:maidsafe.nfs_vault.protobuf.AccountRemoval)
 private:
  inline void set_has_random_data();
  inline void clear_has_random_data();
  inline void set_has_public_anmaid_name();
  inline void clear_has_public_anmaid_name();
  inline void set_has_signature();
  inline void clear_has_signature();

  ::std::string* random_data_;
  ::std::string* public_anmaid_name_;
  ::std::string* signature_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_maidsafe_2fnfs_2fvault_2faccount_5fremoval_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_maidsafe_2fnfs_2fvault_2faccount_5fremoval_2eproto();
  #endif
  friend void protobuf_AssignDesc_maidsafe_2fnfs_2fvault_2faccount_5fremoval_2eproto();
  friend void protobuf_ShutdownFile_maidsafe_2fnfs_2fvault_2faccount_5fremoval_2eproto();

  void InitAsDefaultInstance();
  static AccountRemoval* default_instance_;
};
// ===================================================================


// ===================================================================

// AccountRemoval

// required bytes random_data = 1;
inline bool AccountRemoval::has_random_data() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AccountRemoval::set_has_random_data() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AccountRemoval::clear_has_random_data() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AccountRemoval::clear_random_data() {
  if (random_data_ != &::google::protobuf::internal::GetEmptyString()) {
    random_data_->clear();
  }
  clear_has_random_data();
}
inline const ::std::string& AccountRemoval::random_data() const {
  return *random_data_;
}
inline void AccountRemoval::set_random_data(const ::std::string& value) {
  set_has_random_data();
  if (random_data_ == &::google::protobuf::internal::GetEmptyString()) {
    random_data_ = new ::std::string;
  }
  random_data_->assign(value);
}
inline void AccountRemoval::set_random_data(const char* value) {
  set_has_random_data();
  if (random_data_ == &::google::protobuf::internal::GetEmptyString()) {
    random_data_ = new ::std::string;
  }
  random_data_->assign(value);
}
inline void AccountRemoval::set_random_data(const void* value, size_t size) {
  set_has_random_data();
  if (random_data_ == &::google::protobuf::internal::GetEmptyString()) {
    random_data_ = new ::std::string;
  }
  random_data_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* AccountRemoval::mutable_random_data() {
  set_has_random_data();
  if (random_data_ == &::google::protobuf::internal::GetEmptyString()) {
    random_data_ = new ::std::string;
  }
  return random_data_;
}
inline ::std::string* AccountRemoval::release_random_data() {
  clear_has_random_data();
  if (random_data_ == &::google::protobuf::internal::GetEmptyString()) {
    return NULL;
  } else {
    ::std::string* temp = random_data_;
    random_data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyString());
    return temp;
  }
}
inline void AccountRemoval::set_allocated_random_data(::std::string* random_data) {
  if (random_data_ != &::google::protobuf::internal::GetEmptyString()) {
    delete random_data_;
  }
  if (random_data) {
    set_has_random_data();
    random_data_ = random_data;
  } else {
    clear_has_random_data();
    random_data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyString());
  }
}

// required bytes public_anmaid_name = 2;
inline bool AccountRemoval::has_public_anmaid_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AccountRemoval::set_has_public_anmaid_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AccountRemoval::clear_has_public_anmaid_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AccountRemoval::clear_public_anmaid_name() {
  if (public_anmaid_name_ != &::google::protobuf::internal::GetEmptyString()) {
    public_anmaid_name_->clear();
  }
  clear_has_public_anmaid_name();
}
inline const ::std::string& AccountRemoval::public_anmaid_name() const {
  return *public_anmaid_name_;
}
inline void AccountRemoval::set_public_anmaid_name(const ::std::string& value) {
  set_has_public_anmaid_name();
  if (public_anmaid_name_ == &::google::protobuf::internal::GetEmptyString()) {
    public_anmaid_name_ = new ::std::string;
  }
  public_anmaid_name_->assign(value);
}
inline void AccountRemoval::set_public_anmaid_name(const char* value) {
  set_has_public_anmaid_name();
  if (public_anmaid_name_ == &::google::protobuf::internal::GetEmptyString()) {
    public_anmaid_name_ = new ::std::string;
  }
  public_anmaid_name_->assign(value);
}
inline void AccountRemoval::set_public_anmaid_name(const void* value, size_t size) {
  set_has_public_anmaid_name();
  if (public_anmaid_name_ == &::google::protobuf::internal::GetEmptyString()) {
    public_anmaid_name_ = new ::std::string;
  }
  public_anmaid_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* AccountRemoval::mutable_public_anmaid_name() {
  set_has_public_anmaid_name();
  if (public_anmaid_name_ == &::google::protobuf::internal::GetEmptyString()) {
    public_anmaid_name_ = new ::std::string;
  }
  return public_anmaid_name_;
}
inline ::std::string* AccountRemoval::release_public_anmaid_name() {
  clear_has_public_anmaid_name();
  if (public_anmaid_name_ == &::google::protobuf::internal::GetEmptyString()) {
    return NULL;
  } else {
    ::std::string* temp = public_anmaid_name_;
    public_anmaid_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyString());
    return temp;
  }
}
inline void AccountRemoval::set_allocated_public_anmaid_name(::std::string* public_anmaid_name) {
  if (public_anmaid_name_ != &::google::protobuf::internal::GetEmptyString()) {
    delete public_anmaid_name_;
  }
  if (public_anmaid_name) {
    set_has_public_anmaid_name();
    public_anmaid_name_ = public_anmaid_name;
  } else {
    clear_has_public_anmaid_name();
    public_anmaid_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyString());
  }
}

// required bytes signature = 3;
inline bool AccountRemoval::has_signature() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void AccountRemoval::set_has_signature() {
  _has_bits_[0] |= 0x00000004u;
}
inline void AccountRemoval::clear_has_signature() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void AccountRemoval::clear_signature() {
  if (signature_ != &::google::protobuf::internal::GetEmptyString()) {
    signature_->clear();
  }
  clear_has_signature();
}
inline const ::std::string& AccountRemoval::signature() const {
  return *signature_;
}
inline void AccountRemoval::set_signature(const ::std::string& value) {
  set_has_signature();
  if (signature_ == &::google::protobuf::internal::GetEmptyString()) {
    signature_ = new ::std::string;
  }
  signature_->assign(value);
}
inline void AccountRemoval::set_signature(const char* value) {
  set_has_signature();
  if (signature_ == &::google::protobuf::internal::GetEmptyString()) {
    signature_ = new ::std::string;
  }
  signature_->assign(value);
}
inline void AccountRemoval::set_signature(const void* value, size_t size) {
  set_has_signature();
  if (signature_ == &::google::protobuf::internal::GetEmptyString()) {
    signature_ = new ::std::string;
  }
  signature_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* AccountRemoval::mutable_signature() {
  set_has_signature();
  if (signature_ == &::google::protobuf::internal::GetEmptyString()) {
    signature_ = new ::std::string;
  }
  return signature_;
}
inline ::std::string* AccountRemoval::release_signature() {
  clear_has_signature();
  if (signature_ == &::google::protobuf::internal::GetEmptyString()) {
    return NULL;
  } else {
    ::std::string* temp = signature_;
    signature_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyString());
    return temp;
  }
}
inline void AccountRemoval::set_allocated_signature(::std::string* signature) {
  if (signature_ != &::google::protobuf::internal::GetEmptyString()) {
    delete signature_;
  }
  if (signature) {
    set_has_signature();
    signature_ = signature;
  } else {
    clear_has_signature();
    signature_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyString());
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace nfs_vault
}  // namespace maidsafe

// @@protoc_insertion_point(global_scope)

#ifdef _MSC_VER
#  pragma warning(pop)
#endif

#endif  // PROTOBUF_maidsafe_2fnfs_2fvault_2faccount_5fremoval_2eproto__INCLUDED
