// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: maidsafe/vault/data_manager/action_put.proto

#ifndef PROTOBUF_maidsafe_2fvault_2fdata_5fmanager_2faction_5fput_2eproto__INCLUDED
#define PROTOBUF_maidsafe_2fvault_2fdata_5fmanager_2faction_5fput_2eproto__INCLUDED

#ifdef _MSC_VER
#  pragma warning(push)
#  pragma warning(disable: 4127 4244 4267)
#endif

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace maidsafe {
namespace vault {
namespace protobuf {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_maidsafe_2fvault_2fdata_5fmanager_2faction_5fput_2eproto();
void protobuf_AssignDesc_maidsafe_2fvault_2fdata_5fmanager_2faction_5fput_2eproto();
void protobuf_ShutdownFile_maidsafe_2fvault_2fdata_5fmanager_2faction_5fput_2eproto();

class ActionDataManagerPut;

// ===================================================================

class ActionDataManagerPut : public ::google::protobuf::MessageLite {
 public:
  ActionDataManagerPut();
  virtual ~ActionDataManagerPut();

  ActionDataManagerPut(const ActionDataManagerPut& from);

  inline ActionDataManagerPut& operator=(const ActionDataManagerPut& from) {
    CopyFrom(from);
    return *this;
  }

  static const ActionDataManagerPut& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const ActionDataManagerPut* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(ActionDataManagerPut* other);

  // implements Message ----------------------------------------------

  ActionDataManagerPut* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const ActionDataManagerPut& from);
  void MergeFrom(const ActionDataManagerPut& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 size = 1;
  inline bool has_size() const;
  inline void clear_size();
  static const int kSizeFieldNumber = 1;
  inline ::google::protobuf::uint64 size() const;
  inline void set_size(::google::protobuf::uint64 value);

  // required int32 message_id = 2;
  inline bool has_message_id() const;
  inline void clear_message_id();
  static const int kMessageIdFieldNumber = 2;
  inline ::google::protobuf::int32 message_id() const;
  inline void set_message_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:maidsafe.vault.protobuf.ActionDataManagerPut)
 private:
  inline void set_has_size();
  inline void clear_has_size();
  inline void set_has_message_id();
  inline void clear_has_message_id();

  ::google::protobuf::uint64 size_;
  ::google::protobuf::int32 message_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_maidsafe_2fvault_2fdata_5fmanager_2faction_5fput_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_maidsafe_2fvault_2fdata_5fmanager_2faction_5fput_2eproto();
  #endif
  friend void protobuf_AssignDesc_maidsafe_2fvault_2fdata_5fmanager_2faction_5fput_2eproto();
  friend void protobuf_ShutdownFile_maidsafe_2fvault_2fdata_5fmanager_2faction_5fput_2eproto();

  void InitAsDefaultInstance();
  static ActionDataManagerPut* default_instance_;
};
// ===================================================================


// ===================================================================

// ActionDataManagerPut

// required uint64 size = 1;
inline bool ActionDataManagerPut::has_size() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ActionDataManagerPut::set_has_size() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ActionDataManagerPut::clear_has_size() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ActionDataManagerPut::clear_size() {
  size_ = GOOGLE_ULONGLONG(0);
  clear_has_size();
}
inline ::google::protobuf::uint64 ActionDataManagerPut::size() const {
  return size_;
}
inline void ActionDataManagerPut::set_size(::google::protobuf::uint64 value) {
  set_has_size();
  size_ = value;
}

// required int32 message_id = 2;
inline bool ActionDataManagerPut::has_message_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ActionDataManagerPut::set_has_message_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ActionDataManagerPut::clear_has_message_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ActionDataManagerPut::clear_message_id() {
  message_id_ = 0;
  clear_has_message_id();
}
inline ::google::protobuf::int32 ActionDataManagerPut::message_id() const {
  return message_id_;
}
inline void ActionDataManagerPut::set_message_id(::google::protobuf::int32 value) {
  set_has_message_id();
  message_id_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace vault
}  // namespace maidsafe

// @@protoc_insertion_point(global_scope)

#ifdef _MSC_VER
#  pragma warning(pop)
#endif

#endif  // PROTOBUF_maidsafe_2fvault_2fdata_5fmanager_2faction_5fput_2eproto__INCLUDED
